/* This file is automatically generated by Lemon from input grammar
** source file "SkLemonSpreadSheet.y".
*/
/*
** 2000-05-29
**
** The author disclaims copyright to this source code.  In place of
** a legal notice, here is a blessing:
**
**    May you do good and not evil.
**    May you find forgiveness for yourself and forgive others.
**    May you share freely, never taking more than you give.
**
*************************************************************************
** Driver template for the LEMON parser generator.
**
** The "lemon" program processes an LALR(1) input grammar file, then uses
** this template to construct a parser.  The "lemon" program inserts text
** at each "%%" line.  Also, any "P-a-r-s-e" identifer prefix (without the
** interstitial "-" characters) contained in this template is changed into
** the value of the %name directive from the grammar.  Otherwise, the content
** of this template is copied straight through into the generate parser
** source file.
**
** The following is the concatenation of all %include directives from the
** input grammar file:
*/
/************ Begin %include sections from the grammar ************************/
#include "../include/SkLemonSpreadSheet.hpp"

#define _debugparser
#define _debuglex
using namespace SkSpreadSheet;

// Callback for allocator
void* ParseAlloc(void * (tSize));
void  ParseFree(void *,void  (void *));
// Cell & Range, position Lexer and position LemonParser ======================
tInt wIndLex=0;

// For Error ==================================================================
tInt wLexLine=0;
tInt wLexColumn =0;

// Prédefinition lemon ========================================================
void Parse(
  void *yyp,      /* The parser */
  int yymajor,    /* The major token code number */
  tToken yyminor,   /* The value for the token  see %token_type {tToken} */
  tLemonInterface* sFormula /* see %extra_argument { tLemonInterface *wInterface } */
);
// columnid
tLexerToken* wColumnIdToken=nullptr;

void ParseTrace(FILE* TraceFILE, char* zTracePrompt);

using namespace SkRoot;
  void token_destructor(tToken sToken) { (void)sToken; }
  
namespace SkSpreadSheet {

    void ParserInit(tLemonInterface* sInterface) {
      sInterface->LemonParser(ParseAlloc (malloc));
#ifdef debugparser
      // Debug config
      ParseTrace(stdout, "Parser->");
#endif
    }

    void ParserDone(tLemonInterface* sInterface) {
      ParseFree(sInterface->LemonParser(), free );
      sInterface->LemonParser(nullptr);
    }

    tBool ParserRun(tLemonInterface* sInterface,const tChar* sCode) {
      // Debug Lemon
      //ParseTrace(stdout, "parser >>");

      // Token Lemon
      tToken wToken;

      wIndLex=0;
      
      sInterface->ClearCompil();
      // Create Lexer
      tLexer wLex(sCode);
      // Add Separator Decimal & Arg
      tLocale* wLocale=tApplication::Instance()->Locale();
      wLex.SeparatorArg(wLocale->Arg());
      wLex.SeparatorDecimal(wLocale->Decimal());
      tLexerToken wLexerToken;

      // Loop until End or Unexpected caracter 
      for (wLexerToken = wLex.next();!wLexerToken.is_one_of(tKind::End, tKind::Unexpected); wLexerToken = wLex.next()) {
            //std::cout << "Lex -->" << wLexerToken << endl;
            // Appel la fin
            wToken.m_Token=new tLexerToken(wLexerToken);
            wToken.m_Column = wLex.Column();
            wToken.m_Line = wLex.Line();
            wToken.m_Token->IndLex(wIndLex++);
            wLexColumn=wToken.m_Column;
            wLexLine=wToken.m_Line;

            tInt wCstLemon = 0;
            switch (wToken.m_Token->Kind()) {
            case tKind::Integer: wCstLemon = INTEGER; break;
            case tKind::Float: wCstLemon = FLOAT;  break;
            case tKind::Bool: wCstLemon = BOOL; break;
            case tKind::Plus: wCstLemon = PLUS; break;
            case tKind::Minus: wCstLemon = MINUS; break;
            case tKind::Times: wCstLemon = TIMES; break;
            case tKind::Divide: wCstLemon = DIVIDE; break;
            case tKind::Equal: wCstLemon = EQUAL; break;
            case tKind::NotEqual: wCstLemon = NOTEQUAL; break;
            case tKind::GreaterThan: wCstLemon = GREATER; break;
            case tKind::GreaterThanOrEqual: wCstLemon = GREATEREQUAL; break;
            case tKind::LessThan: wCstLemon = LESS; break;
            case tKind::LessThanOrEqual: wCstLemon = LESSEQUAL; break;
            case tKind::Sheet: {
              wCstLemon = SHEET;
              sInterface->SheetByToken(&wLexerToken);
              break;
            }
            case tKind::Cell: wCstLemon = CELL; break;
            case tKind::Hash: wCstLemon = HASH; break;
            
            case tKind::LeftParen : wCstLemon = LEFTPARENT; break;
            case tKind::RightParen : wCstLemon = RIGHTPARENT; break;
            case tKind::LeftSquare  : {
                  wCstLemon = LEFTSQUARE;  
                  break;
            }
            case tKind::RightSquare  : {
                  wCstLemon = RIGHTSQUARE; 
                  break;
            }
            case tKind::Identifier: {
                tString wResult = wToken.m_Token->Lexeme();
                if (wResult == "@") {
                  wCstLemon = AT;
                  break;
                }
                // Is reserved word and or not etc...
                tString wUppercase=wResult;
                std::transform(wResult.begin(), wResult.end(),wUppercase.begin(), ::toupper);
                tInt wRes = sInterface->Id(wUppercase);
                if (wRes != -1) {
                  // Function SpreadSheet
                  wCstLemon = wRes;
                } else if (wUppercase == "LET") {
                  // LET is parsed by a dedicated grammar rule (local scope), not the generic ID '(' path.
                  wCstLemon = LET;
                } else {
                  wCstLemon = ID;
                }
                break;
            }
            case tKind::LabelDouble: wCstLemon = LABELDQ; break; 
            case tKind::LabelSimple: wCstLemon = LABELSQ; break;
            case tKind::LabelSquare: wCstLemon = LABELSQUARE; break; 

            case tKind::LeftCurly: wCstLemon = LEFTCURLY; break;
            case tKind::RightCurly: wCstLemon = RIGHTCURLY; break;

            case tKind::ErrorRef: {
                wCstLemon = ERRORREF;
                break;
            }
            case tKind::ErrorName: {
                wCstLemon = ERRORNAME;
                break;
            } 

  
            case tKind::Ampersand  : wCstLemon = AMPERSAND; break;
            case tKind::Percent    : wCstLemon = PERCENT; break;
            //case tKind::Exclamation: wCstLemon = EXCLAMATION; break;
            case tKind::Attribute : wCstLemon = ATTRIBUTE; break;
            //case tKind::NewLine: wCstLemon = NEWLINE; break;
            case tKind::Colon: wCstLemon = COLON; break;
            case tKind::Comma: wCstLemon = COMMA; break;
            case tKind::Semicolon: wCstLemon = SEMICOLON; break;
            case tKind::Pipe: wCstLemon = PIPE; break;
            default: {
                sInterface->CompilError(tErrorFormula::t_SyntaxError);
                sInterface->Error("Syntax error !",wLexLine,wLexColumn);
                break;
            }
            }
          
#ifdef debuglex
           tLexerToken* wDebugLexerToken=wToken.m_Token;
           cout << wLexColumn <<  " Lex -->" << wDebugLexerToken->Kind() << ":" <<   wDebugLexerToken->Lexeme();
           cout << endl;
#endif
            Parse(sInterface->LemonParser(), wCstLemon, wToken,sInterface);
            if (sInterface->CompilError()!=tErrorFormula::t_None) { break; }
      }
      if (sInterface->CompilError() == tErrorFormula::t_None) {
        if (wLex.ArrayLiteralDepth() != 0 || wLex.InPipeLiteral()) {
          sInterface->CompilError(tErrorFormula::t_SyntaxError);
          sInterface->Error("Unbalanced array literal { } or | |", wLexLine, wLexColumn);
        }
      }
      Parse (sInterface->LemonParser(), END, wToken,sInterface);

      if (wLexerToken.Kind()==tKind::Unexpected) {
        sInterface->CompilError(tErrorFormula::t_SyntaxError);
        sInterface->Error("Caracter Invalid !",wLexLine,wLexColumn);
      }
      Parse(sInterface->LemonParser(), 0, wToken,sInterface);
    
      return(sInterface->CompilError()==tErrorFormula::t_None);
    }
  } // End of namespace
  
/**************** End of %include directives **********************************/
/* These constants specify the various numeric values for terminal symbols.
***************** Begin token definitions *************************************/
#ifndef ID
#define ID                              1
#define LABELDQ                         2
#define LABELSQ                         3
#define LABELSQUARE                     4
#define CELL                            5
#define ATTRIBUTE                       6
#define ERRORREF                        7
#define ERRORNAME                       8
#define PERCENT                         9
#define AT                             10
#define HASH                           11
#define EQUAL                          12
#define NOTEQUAL                       13
#define GREATER                        14
#define GREATEREQUAL                   15
#define LESS                           16
#define LESSEQUAL                      17
#define AMPERSAND                      18
#define PLUS                           19
#define MINUS                          20
#define TIMES                          21
#define DIVIDE                         22
#define MOD                            23
#define COMMA                          24
#define SEMICOLON                      25
#define PIPE                           26
#define LEFTSQUARE                     27
#define LEFTPARENT                     28
#define RIGHTSQUARE                    29
#define RIGHTPARENT                    30
#define LEFTCURLY                      31
#define RIGHTCURLY                     32
#define END                            33
#define INTEGER                        34
#define FLOAT                          35
#define BOOL                           36
#define SHEET                          37
#define COLON                          38
#define LET                            39
#endif
/**************** End token definitions ***************************************/

/* The next sections is a series of control #defines.
** various aspects of the generated parser.
**    YYCODETYPE         is the data type used to store the integer codes
**                       that represent terminal and non-terminal symbols.
**                       "unsigned char" is used if there are fewer than
**                       256 symbols.  Larger types otherwise.
**    YYNOCODE           is a number of type YYCODETYPE that is not used for
**                       any terminal or nonterminal symbol.
**    YYFALLBACK         If defined, this indicates that one or more tokens
**                       (also known as: "terminal symbols") have fall-back
**                       values which should be used if the original symbol
**                       would not parse.  This permits keywords to sometimes
**                       be used as identifiers, for example.
**    YYACTIONTYPE       is the data type used for "action codes" - numbers
**                       that indicate what to do in response to the next
**                       token.
**    ParseTOKENTYPE     is the data type used for minor type for terminal
**                       symbols.  Background: A "minor type" is a semantic
**                       value associated with a terminal or non-terminal
**                       symbols.  For example, for an "ID" terminal symbol,
**                       the minor type might be the name of the identifier.
**                       Each non-terminal can have a different minor type.
**                       Terminal symbols all have the same minor type, though.
**                       This macros defines the minor type for terminal 
**                       symbols.
**    YYMINORTYPE        is the data type used for all minor types.
**                       This is typically a union of many types, one of
**                       which is ParseTOKENTYPE.  The entry in the union
**                       for terminal symbols is called "yy0".
**    YYSTACKDEPTH       is the maximum depth of the parser's stack.  If
**                       zero the stack is dynamically sized using realloc()
**    ParseARG_SDECL     A static variable declaration for the %extra_argument
**    ParseARG_PDECL     A parameter declaration for the %extra_argument
**    ParseARG_PARAM     Code to pass %extra_argument as a subroutine parameter
**    ParseARG_STORE     Code to store %extra_argument into yypParser
**    ParseARG_FETCH     Code to extract %extra_argument from yypParser
**    ParseCTX_*         As ParseARG_ except for %extra_context
**    YYERRORSYMBOL      is the code number of the error symbol.  If not
**                       defined, then do no error processing.
**    YYNSTATE           the combined number of states.
**    YYNRULE            the number of rules in the grammar
**    YYNTOKEN           Number of terminal symbols
**    YY_MAX_SHIFT       Maximum value for shift actions
**    YY_MIN_SHIFTREDUCE Minimum value for shift-reduce actions
**    YY_MAX_SHIFTREDUCE Maximum value for shift-reduce actions
**    YY_ERROR_ACTION    The yy_action[] code for syntax error
**    YY_ACCEPT_ACTION   The yy_action[] code for accept
**    YY_NO_ACTION       The yy_action[] code for no-op
**    YY_MIN_REDUCE      Minimum value for reduce actions
**    YY_MAX_REDUCE      Maximum value for reduce actions
*/
#ifndef INTERFACE
# define INTERFACE 1
#endif
/************* Begin control #defines *****************************************/
#define YYCODETYPE unsigned char
#define YYNOCODE 64
#define YYACTIONTYPE unsigned short int
#define ParseTOKENTYPE tToken
typedef union {
  int yyinit;
  ParseTOKENTYPE yy0;
} YYMINORTYPE;
#ifndef YYSTACKDEPTH
#define YYSTACKDEPTH 100
#endif
#define ParseARG_SDECL  tLemonInterface *wInterface ;
#define ParseARG_PDECL , tLemonInterface *wInterface 
#define ParseARG_PARAM ,wInterface 
#define ParseARG_FETCH  tLemonInterface *wInterface =yypParser->wInterface ;
#define ParseARG_STORE yypParser->wInterface =wInterface ;
#define ParseCTX_SDECL
#define ParseCTX_PDECL
#define ParseCTX_PARAM
#define ParseCTX_FETCH
#define ParseCTX_STORE
#define YYNSTATE             94
#define YYNRULE              103
#define YYNRULE_WITH_ACTION  85
#define YYNTOKEN             40
#define YY_MAX_SHIFT         93
#define YY_MIN_SHIFTREDUCE   162
#define YY_MAX_SHIFTREDUCE   264
#define YY_ERROR_ACTION      265
#define YY_ACCEPT_ACTION     266
#define YY_NO_ACTION         267
#define YY_MIN_REDUCE        268
#define YY_MAX_REDUCE        370
/************* End control #defines *******************************************/
#define YY_NLOOKAHEAD ((int)(sizeof(yy_lookahead)/sizeof(yy_lookahead[0])))

/* Define the yytestcase() macro to be a no-op if is not already defined
** otherwise.
**
** Applications can choose to define yytestcase() in the %include section
** to a macro that can assist in verifying code coverage.  For production
** code the yytestcase() macro should be turned off.  But it is useful
** for testing.
*/
#ifndef yytestcase
# define yytestcase(X)
#endif


/* Next are the tables used to determine what action to take based on the
** current state and lookahead token.  These tables are used to implement
** functions that take a state number and lookahead value and return an
** action integer.  
**
** Suppose the action integer is N.  Then the action is determined as
** follows
**
**   0 <= N <= YY_MAX_SHIFT             Shift N.  That is, push the lookahead
**                                      token onto the stack and goto state N.
**
**   N between YY_MIN_SHIFTREDUCE       Shift to an arbitrary state then
**     and YY_MAX_SHIFTREDUCE           reduce by rule N-YY_MIN_SHIFTREDUCE.
**
**   N == YY_ERROR_ACTION               A syntax error has occurred.
**
**   N == YY_ACCEPT_ACTION              The parser accepts its input.
**
**   N == YY_NO_ACTION                  No such action.  Denotes unused
**                                      slots in the yy_action[] table.
**
**   N between YY_MIN_REDUCE            Reduce by rule N-YY_MIN_REDUCE
**     and YY_MAX_REDUCE
**
** The action table is constructed as a single large table named yy_action[].
** Given state S and lookahead X, the action is computed as either:
**
**    (A)   N = yy_action[ yy_shift_ofst[S] + X ]
**    (B)   N = yy_default[S]
**
** The (A) formula is preferred.  The B formula is used instead if
** yy_lookahead[yy_shift_ofst[S]+X] is not equal to X.
**
** The formulas above are for computing the action when the lookahead is
** a terminal symbol.  If the lookahead is a non-terminal (as occurs after
** a reduce action) then the yy_reduce_ofst[] array is used in place of
** the yy_shift_ofst[] array.
**
** The following are the tables generated in this section:
**
**  yy_action[]        A single table containing all actions.
**  yy_lookahead[]     A table containing the lookahead for each entry in
**                     yy_action.  Used to detect hash collisions.
**  yy_shift_ofst[]    For each state, the offset into yy_action for
**                     shifting terminals.
**  yy_reduce_ofst[]   For each state, the offset into yy_action for
**                     shifting non-terminals after a reduce.
**  yy_default[]       Default action for each state.
**
*********** Begin parsing tables **********************************************/
#define YY_ACTTAB_COUNT (774)
static const YYACTIONTYPE yy_action[] = {
 /*     0 */   353,   38,   91,   92,  185,   41,   44,   46,   49,  164,
 /*    10 */    81,   86,   60,  365,   90,  192,   60,  196,  364,   25,
 /*    20 */    27,   45,   88,    3,  310,   42,  235,   48,   15,   30,
 /*    30 */    29,  234,   39,   34,  173,  174,  175,   76,  355,   84,
 /*    40 */    13,   38,   91,   92,  185,   41,    4,   46,   49,  285,
 /*    50 */    81,  210,   70,   36,   70,   35,   87,  253,  252,   25,
 /*    60 */    27,   23,   24,   28,   26,  250,  235,   14,   15,  285,
 /*    70 */   190,  234,  260,  261,  173,  174,  175,   76,  242,   84,
 /*    80 */   294,   33,   91,   92,  185,   41,  187,   46,   49,  186,
 /*    90 */    81,   71,   36,   71,   35,   43,   43,   40,  295,   25,
 /*   100 */    27,   87,  253,  252,   90,  203,  235,  287,   15,  266,
 /*   110 */     1,  234,  312,    2,  173,  174,  175,   76,  210,   84,
 /*   120 */     6,   21,   20,   19,   18,   17,   16,   22,   23,   24,
 /*   130 */    28,   26,  193,   14,  260,  261,  194,  210,  195,  246,
 /*   140 */    21,   20,   19,   18,   17,   16,   22,   23,   24,   28,
 /*   150 */    26,  232,  233,  237,   47,  250,  210,  250,  222,   21,
 /*   160 */    20,   19,   18,   17,   16,   22,   23,   24,   28,   26,
 /*   170 */   210,  230,  231,  265,  265,  265,  265,  265,  265,   22,
 /*   180 */    23,   24,   28,   26,   68,  250,   90,  283,   68,   77,
 /*   190 */   210,   93,   37,  288,   88,    3,  357,   50,  250,  232,
 /*   200 */   233,   30,   29,  284,   60,   34,   90,  236,   60,   90,
 /*   210 */   228,  229,  282,  286,   88,    3,   85,  313,    5,  244,
 /*   220 */   241,   30,   29,   31,   39,   34,  241,   60,   32,   90,
 /*   230 */    78,   60,  201,  172,  357,   50,  250,   88,    3,  308,
 /*   240 */   359,  250,  358,  162,   30,   29,  191,   39,   34,   60,
 /*   250 */   267,   90,  267,   60,  260,  261,  267,  267,  241,   88,
 /*   260 */     3,  311,  267,  227,  226,  210,   30,   29,   78,   39,
 /*   270 */    34,  267,   51,   89,   90,  267,   51,   28,   26,  267,
 /*   280 */    79,   80,   88,    3,  267,  267,  267,  267,  267,   30,
 /*   290 */    29,  267,  267,   34,  370,  223,  224,  225,  267,  199,
 /*   300 */    53,  267,   90,  198,   53,  200,  267,  267,  267,  267,
 /*   310 */    88,    3,  267,  267,  267,  267,  267,   30,   29,  267,
 /*   320 */   267,   34,  267,   54,  267,   90,  267,   54,  267,  267,
 /*   330 */   267,  267,  267,   88,    3,   55,  267,   90,  267,   55,
 /*   340 */    30,   29,  267,  267,   34,   88,    3,  267,  267,  267,
 /*   350 */   267,  267,   30,   29,  267,  267,   34,  267,   56,  267,
 /*   360 */    90,  267,   56,  267,  267,  267,  267,  267,   88,    3,
 /*   370 */   267,  267,  267,  267,  267,   30,   29,  267,   57,   34,
 /*   380 */    90,  267,   57,  267,  267,  267,  267,  267,   88,    3,
 /*   390 */   267,  267,  267,  267,  267,   30,   29,  267,  267,   34,
 /*   400 */   267,   58,  267,   90,  267,   58,  267,  267,  267,  267,
 /*   410 */   267,   88,    3,  267,  267,  267,  267,  267,   30,   29,
 /*   420 */   267,   59,   34,   90,  267,   59,  267,  267,  267,  267,
 /*   430 */   267,   88,    3,  267,  267,  267,  267,  267,   30,   29,
 /*   440 */   267,  267,   34,  267,   61,  267,   90,  267,   61,  267,
 /*   450 */   267,  267,  267,  267,   88,    3,  267,  267,  267,  267,
 /*   460 */   267,   30,   29,  267,   52,   34,   90,  267,   52,  267,
 /*   470 */   267,  267,  267,  267,   88,    3,  267,  267,  267,  267,
 /*   480 */   267,   30,   29,  267,  267,   34,  267,   62,  267,   90,
 /*   490 */   267,   62,  267,  267,  267,  267,  267,   88,    3,  267,
 /*   500 */   267,  267,  267,  267,   30,   29,  267,   63,   34,   90,
 /*   510 */   267,   63,  267,  267,  267,  267,  267,   88,    3,  267,
 /*   520 */   267,  267,  267,  267,   30,   29,  267,  267,   34,  267,
 /*   530 */    64,  267,   90,  267,   64,  267,  267,  267,  267,  267,
 /*   540 */    88,    3,  267,  267,  267,  267,  267,   30,   29,  267,
 /*   550 */    65,   34,   90,  267,   65,  267,  267,  267,  267,  267,
 /*   560 */    88,    3,  267,  267,  267,  267,  267,   30,   29,  267,
 /*   570 */   267,   34,  267,   66,  267,   90,  267,   66,  267,  267,
 /*   580 */   267,  267,  267,   88,    3,  267,  267,  267,  267,  267,
 /*   590 */    30,   29,  267,   67,   34,   90,  267,   67,  267,  267,
 /*   600 */   267,  267,  267,   88,    3,  267,  267,  267,  267,  267,
 /*   610 */    30,   29,  267,  267,   34,  267,   69,  267,   90,  267,
 /*   620 */    69,  267,  267,  267,  267,  267,   88,    3,  267,  267,
 /*   630 */   267,  267,  267,   30,   29,  267,   72,   34,   90,  267,
 /*   640 */    72,  267,  267,  267,  267,  267,   88,    3,  267,  267,
 /*   650 */   267,  267,  267,   30,   29,  267,  267,   34,  267,   73,
 /*   660 */   267,   90,  267,   73,  267,  267,  267,  267,  267,   88,
 /*   670 */     3,  267,  267,  267,  267,  267,   30,   29,  267,   74,
 /*   680 */    34,   90,  267,   74,  267,  267,  267,  267,  267,   88,
 /*   690 */     3,  267,  267,  267,  267,  267,   30,   29,  267,  267,
 /*   700 */    34,  267,   83,  267,   90,  267,   83,  267,  267,  267,
 /*   710 */   267,  267,   88,    3,  267,  267,  267,  267,  267,   30,
 /*   720 */    29,  267,   75,   34,   90,  267,   75,  267,  267,  267,
 /*   730 */   267,  267,   88,    3,  267,  267,  267,  267,  267,   30,
 /*   740 */    29,  267,  267,   34,  267,   82,  267,   90,  267,   82,
 /*   750 */   267,  267,  267,  267,  267,   88,    3,  267,  267,  267,
 /*   760 */   267,  267,   30,   29,  267,  267,   34,  267,   12,   11,
 /*   770 */    10,    9,    8,    7,
};
static const YYCODETYPE yy_lookahead[] = {
 /*     0 */     0,    1,    2,    3,    4,    5,    1,    7,    8,    9,
 /*    10 */    10,    1,   40,   53,   42,    5,   44,    7,   53,   19,
 /*    20 */    20,    1,   50,   51,   52,    5,   26,    7,   28,   57,
 /*    30 */    58,   31,   60,   61,   34,   35,   36,   37,   49,   39,
 /*    40 */    59,    1,    2,    3,    4,    5,   51,    7,    8,   41,
 /*    50 */    10,    9,   53,   54,   55,   56,    1,    2,    3,   19,
 /*    60 */    20,   19,   20,   21,   22,    6,   26,   59,   28,   41,
 /*    70 */    11,   31,   24,   25,   34,   35,   36,   37,   30,   39,
 /*    80 */    41,    1,    2,    3,    4,    5,    1,    7,    8,    4,
 /*    90 */    10,   53,   54,   55,   56,   62,   63,   38,   41,   19,
 /*   100 */    20,    1,    2,    3,   42,    5,   26,   41,   28,   45,
 /*   110 */    46,   31,   50,   51,   34,   35,   36,   37,    9,   39,
 /*   120 */    59,   12,   13,   14,   15,   16,   17,   18,   19,   20,
 /*   130 */    21,   22,    1,   59,   24,   25,    5,    9,    7,   30,
 /*   140 */    12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
 /*   150 */    22,   24,   25,   26,    5,    6,    9,    6,   30,   12,
 /*   160 */    13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
 /*   170 */     9,   34,   35,   12,   13,   14,   15,   16,   17,   18,
 /*   180 */    19,   20,   21,   22,   40,    6,   42,   41,   44,   38,
 /*   190 */     9,   47,   48,   41,   50,   51,    4,    5,    6,   24,
 /*   200 */    25,   57,   58,   41,   40,   61,   42,   32,   44,   42,
 /*   210 */    34,   35,   41,   41,   50,   51,   52,   50,   51,   28,
 /*   220 */    28,   57,   58,   38,   60,   61,   28,   40,   38,   42,
 /*   230 */    38,   44,    5,    4,    4,    5,    6,   50,   51,   52,
 /*   240 */     4,    6,    4,   33,   57,   58,   11,   60,   61,   40,
 /*   250 */    64,   42,   64,   44,   24,   25,   64,   64,   28,   50,
 /*   260 */    51,   52,   64,    2,    3,    9,   57,   58,   38,   60,
 /*   270 */    61,   64,   40,   38,   42,   64,   44,   21,   22,   64,
 /*   280 */    19,   20,   50,   51,   64,   64,   64,   64,   64,   57,
 /*   290 */    58,   64,   64,   61,   62,   34,   35,   36,   64,    1,
 /*   300 */    40,   64,   42,    5,   44,    7,   64,   64,   64,   64,
 /*   310 */    50,   51,   64,   64,   64,   64,   64,   57,   58,   64,
 /*   320 */    64,   61,   64,   40,   64,   42,   64,   44,   64,   64,
 /*   330 */    64,   64,   64,   50,   51,   40,   64,   42,   64,   44,
 /*   340 */    57,   58,   64,   64,   61,   50,   51,   64,   64,   64,
 /*   350 */    64,   64,   57,   58,   64,   64,   61,   64,   40,   64,
 /*   360 */    42,   64,   44,   64,   64,   64,   64,   64,   50,   51,
 /*   370 */    64,   64,   64,   64,   64,   57,   58,   64,   40,   61,
 /*   380 */    42,   64,   44,   64,   64,   64,   64,   64,   50,   51,
 /*   390 */    64,   64,   64,   64,   64,   57,   58,   64,   64,   61,
 /*   400 */    64,   40,   64,   42,   64,   44,   64,   64,   64,   64,
 /*   410 */    64,   50,   51,   64,   64,   64,   64,   64,   57,   58,
 /*   420 */    64,   40,   61,   42,   64,   44,   64,   64,   64,   64,
 /*   430 */    64,   50,   51,   64,   64,   64,   64,   64,   57,   58,
 /*   440 */    64,   64,   61,   64,   40,   64,   42,   64,   44,   64,
 /*   450 */    64,   64,   64,   64,   50,   51,   64,   64,   64,   64,
 /*   460 */    64,   57,   58,   64,   40,   61,   42,   64,   44,   64,
 /*   470 */    64,   64,   64,   64,   50,   51,   64,   64,   64,   64,
 /*   480 */    64,   57,   58,   64,   64,   61,   64,   40,   64,   42,
 /*   490 */    64,   44,   64,   64,   64,   64,   64,   50,   51,   64,
 /*   500 */    64,   64,   64,   64,   57,   58,   64,   40,   61,   42,
 /*   510 */    64,   44,   64,   64,   64,   64,   64,   50,   51,   64,
 /*   520 */    64,   64,   64,   64,   57,   58,   64,   64,   61,   64,
 /*   530 */    40,   64,   42,   64,   44,   64,   64,   64,   64,   64,
 /*   540 */    50,   51,   64,   64,   64,   64,   64,   57,   58,   64,
 /*   550 */    40,   61,   42,   64,   44,   64,   64,   64,   64,   64,
 /*   560 */    50,   51,   64,   64,   64,   64,   64,   57,   58,   64,
 /*   570 */    64,   61,   64,   40,   64,   42,   64,   44,   64,   64,
 /*   580 */    64,   64,   64,   50,   51,   64,   64,   64,   64,   64,
 /*   590 */    57,   58,   64,   40,   61,   42,   64,   44,   64,   64,
 /*   600 */    64,   64,   64,   50,   51,   64,   64,   64,   64,   64,
 /*   610 */    57,   58,   64,   64,   61,   64,   40,   64,   42,   64,
 /*   620 */    44,   64,   64,   64,   64,   64,   50,   51,   64,   64,
 /*   630 */    64,   64,   64,   57,   58,   64,   40,   61,   42,   64,
 /*   640 */    44,   64,   64,   64,   64,   64,   50,   51,   64,   64,
 /*   650 */    64,   64,   64,   57,   58,   64,   64,   61,   64,   40,
 /*   660 */    64,   42,   64,   44,   64,   64,   64,   64,   64,   50,
 /*   670 */    51,   64,   64,   64,   64,   64,   57,   58,   64,   40,
 /*   680 */    61,   42,   64,   44,   64,   64,   64,   64,   64,   50,
 /*   690 */    51,   64,   64,   64,   64,   64,   57,   58,   64,   64,
 /*   700 */    61,   64,   40,   64,   42,   64,   44,   64,   64,   64,
 /*   710 */    64,   64,   50,   51,   64,   64,   64,   64,   64,   57,
 /*   720 */    58,   64,   40,   61,   42,   64,   44,   64,   64,   64,
 /*   730 */    64,   64,   50,   51,   64,   64,   64,   64,   64,   57,
 /*   740 */    58,   64,   64,   61,   64,   40,   64,   42,   64,   44,
 /*   750 */    64,   64,   64,   64,   64,   50,   51,   64,   64,   64,
 /*   760 */    64,   64,   57,   58,   64,   64,   61,   64,   12,   13,
 /*   770 */    14,   15,   16,   17,   64,   64,   64,   64,   64,   64,
 /*   780 */    64,   64,   64,   64,   64,   64,   64,   64,   64,   64,
 /*   790 */    64,   64,   64,   64,   64,   64,   64,   64,   64,   64,
 /*   800 */    64,   64,   64,   64,   64,   64,   64,   64,   64,   40,
 /*   810 */    40,   40,   40,   40,
};
#define YY_SHIFT_COUNT    (93)
#define YY_SHIFT_MIN      (0)
#define YY_SHIFT_MAX      (756)
static const unsigned short int yy_shift_ofst[] = {
 /*     0 */   774,    0,   40,   40,   40,   40,   80,   40,   40,   40,
 /*    10 */    40,   40,   40,   40,   40,   40,   40,   40,   40,   40,
 /*    20 */    40,   40,   40,   40,   40,   40,   40,   40,   40,  261,
 /*    30 */   261,  100,   55,  230,    5,  261,  261,  756,  192,   48,
 /*    40 */    10,   59,  235,  110,  110,  149,  151,  179,  179,  179,
 /*    50 */   179,  109,  128,  147,  147,  147,  147,  147,  147,  147,
 /*    60 */   147,  147,  161,  161,  161,  161,  161,  161,  147,   42,
 /*    70 */   127,  175,  256,  256,  256,  256,   20,  131,  298,  137,
 /*    80 */   176,   85,  181,  181,  191,  185,  198,  198,  190,  227,
 /*    90 */   229,  236,  238,  210,
};
#define YY_REDUCE_COUNT (50)
#define YY_REDUCE_MIN   (-40)
#define YY_REDUCE_MAX   (705)
static const short yy_reduce_ofst[] = {
 /*     0 */    64,  144,  -28,  164,  187,  209,  232,  260,  283,  295,
 /*    10 */   318,  338,  361,  381,  404,  424,  447,  467,  490,  510,
 /*    20 */   533,  553,  576,  596,  619,  639,  662,  682,  705,   -1,
 /*    30 */    38,   62,  167,    8,   33,  -40,  -35,  -11,   28,  -19,
 /*    40 */    -5,   39,   57,   61,   74,   66,  146,  152,  162,  171,
 /*    50 */   172,
};
static const YYACTIONTYPE yy_default[] = {
 /*     0 */   354,  265,  368,  368,  368,  368,  265,  265,  265,  265,
 /*    10 */   265,  265,  265,  346,  265,  265,  265,  265,  265,  265,
 /*    20 */   265,  265,  265,  265,  265,  265,  265,  265,  265,  362,
 /*    30 */   362,  265,  265,  277,  265,  265,  265,  265,  277,  265,
 /*    40 */   265,  277,  277,  265,  265,  277,  277,  277,  277,  277,
 /*    50 */   277,  265,  265,  276,  275,  274,  273,  272,  271,  345,
 /*    60 */   344,  351,  327,  326,  325,  324,  323,  322,  269,  321,
 /*    70 */   265,  265,  320,  319,  315,  314,  265,  265,  265,  265,
 /*    80 */   265,  265,  317,  318,  265,  349,  303,  357,  360,  265,
 /*    90 */   265,  290,  289,  265,
};
/********** End of lemon-generated parsing tables *****************************/

/* The next table maps tokens (terminal symbols) into fallback tokens.  
** If a construct like the following:
** 
**      %fallback ID X Y Z.
**
** appears in the grammar, then ID becomes a fallback token for X, Y,
** and Z.  Whenever one of the tokens X, Y, or Z is input to the parser
** but it does not parse, the type of the token is changed to ID and
** the parse is retried before an error is thrown.
**
** This feature can be used, for example, to cause some keywords in a language
** to revert to identifiers if they keyword does not apply in the context where
** it appears.
*/
#ifdef YYFALLBACK
static const YYCODETYPE yyFallback[] = {
};
#endif /* YYFALLBACK */

/* The following structure represents a single element of the
** parser's stack.  Information stored includes:
**
**   +  The state number for the parser at this level of the stack.
**
**   +  The value of the token stored at this level of the stack.
**      (In other words, the "major" token.)
**
**   +  The semantic value stored at this level of the stack.  This is
**      the information used by the action routines in the grammar.
**      It is sometimes called the "minor" token.
**
** After the "shift" half of a SHIFTREDUCE action, the stateno field
** actually contains the reduce action for the second half of the
** SHIFTREDUCE.
*/
struct yyStackEntry {
  YYACTIONTYPE stateno;  /* The state-number, or reduce action in SHIFTREDUCE */
  YYCODETYPE major;      /* The major token value.  This is the code
                         ** number for the token at this stack level */
  YYMINORTYPE minor;     /* The user-supplied minor token value.  This
                         ** is the value of the token  */
};
typedef struct yyStackEntry yyStackEntry;

/* The state of the parser is completely contained in an instance of
** the following structure */
struct yyParser {
  yyStackEntry *yytos;          /* Pointer to top element of the stack */
#ifdef YYTRACKMAXSTACKDEPTH
  int yyhwm;                    /* High-water mark of the stack */
#endif
#ifndef YYNOERRORRECOVERY
  int yyerrcnt;                 /* Shifts left before out of the error */
#endif
  ParseARG_SDECL                /* A place to hold %extra_argument */
  ParseCTX_SDECL                /* A place to hold %extra_context */
#if YYSTACKDEPTH<=0
  int yystksz;                  /* Current side of the stack */
  yyStackEntry *yystack;        /* The parser's stack */
  yyStackEntry yystk0;          /* First stack entry */
#else
  yyStackEntry yystack[YYSTACKDEPTH];  /* The parser's stack */
  yyStackEntry *yystackEnd;            /* Last entry in the stack */
#endif
};
typedef struct yyParser yyParser;

#ifndef NDEBUG
#include <stdio.h>
static FILE *yyTraceFILE = 0;
static char *yyTracePrompt = 0;
#endif /* NDEBUG */

#include <assert.h>

#ifndef NDEBUG
/* 
** Turn parser tracing on by giving a stream to which to write the trace
** and a prompt to preface each trace message.  Tracing is turned off
** by making either argument NULL 
**
** Inputs:
** <ul>
** <li> A FILE* to which trace output should be written.
**      If NULL, then tracing is turned off.
** <li> A prefix string written at the beginning of every
**      line of trace output.  If NULL, then tracing is
**      turned off.
** </ul>
**
** Outputs:
** None.
*/
void ParseTrace(FILE *TraceFILE, char *zTracePrompt){
  yyTraceFILE = TraceFILE;
  yyTracePrompt = zTracePrompt;
  if( yyTraceFILE==0 ) yyTracePrompt = 0;
  else if( yyTracePrompt==0 ) yyTraceFILE = 0;
}
#endif /* NDEBUG */

#if defined(YYCOVERAGE) || !defined(NDEBUG)
/* For tracing shifts, the names of all terminals and nonterminals
** are required.  The following table supplies these names */
static const char *const yyTokenName[] = { 
  /*    0 */ "$",
  /*    1 */ "ID",
  /*    2 */ "LABELDQ",
  /*    3 */ "LABELSQ",
  /*    4 */ "LABELSQUARE",
  /*    5 */ "CELL",
  /*    6 */ "ATTRIBUTE",
  /*    7 */ "ERRORREF",
  /*    8 */ "ERRORNAME",
  /*    9 */ "PERCENT",
  /*   10 */ "AT",
  /*   11 */ "HASH",
  /*   12 */ "EQUAL",
  /*   13 */ "NOTEQUAL",
  /*   14 */ "GREATER",
  /*   15 */ "GREATEREQUAL",
  /*   16 */ "LESS",
  /*   17 */ "LESSEQUAL",
  /*   18 */ "AMPERSAND",
  /*   19 */ "PLUS",
  /*   20 */ "MINUS",
  /*   21 */ "TIMES",
  /*   22 */ "DIVIDE",
  /*   23 */ "MOD",
  /*   24 */ "COMMA",
  /*   25 */ "SEMICOLON",
  /*   26 */ "PIPE",
  /*   27 */ "LEFTSQUARE",
  /*   28 */ "LEFTPARENT",
  /*   29 */ "RIGHTSQUARE",
  /*   30 */ "RIGHTPARENT",
  /*   31 */ "LEFTCURLY",
  /*   32 */ "RIGHTCURLY",
  /*   33 */ "END",
  /*   34 */ "INTEGER",
  /*   35 */ "FLOAT",
  /*   36 */ "BOOL",
  /*   37 */ "SHEET",
  /*   38 */ "COLON",
  /*   39 */ "LET",
  /*   40 */ "expr",
  /*   41 */ "attribute",
  /*   42 */ "tableid",
  /*   43 */ "columnid",
  /*   44 */ "thisrowcol",
  /*   45 */ "main",
  /*   46 */ "in",
  /*   47 */ "state",
  /*   48 */ "percent_prefix",
  /*   49 */ "conditionalformat",
  /*   50 */ "table",
  /*   51 */ "funcBegin",
  /*   52 */ "funcEnd",
  /*   53 */ "listcell",
  /*   54 */ "listcomma",
  /*   55 */ "listliteral",
  /*   56 */ "listsemi",
  /*   57 */ "openbrace",
  /*   58 */ "openpipe",
  /*   59 */ "argsep",
  /*   60 */ "exprList",
  /*   61 */ "letBegin",
  /*   62 */ "letBinding",
  /*   63 */ "letBindings",
};
#endif /* defined(YYCOVERAGE) || !defined(NDEBUG) */

#ifndef NDEBUG
/* For tracing reduce actions, the names of all rules are required.
*/
static const char *const yyRuleName[] = {
 /*   0 */ "in ::= in state END",
 /*   1 */ "state ::= expr",
 /*   2 */ "percent_prefix ::= PERCENT",
 /*   3 */ "conditionalformat ::= EQUAL expr",
 /*   4 */ "conditionalformat ::= NOTEQUAL expr",
 /*   5 */ "conditionalformat ::= GREATER expr",
 /*   6 */ "conditionalformat ::= GREATEREQUAL expr",
 /*   7 */ "conditionalformat ::= LESS expr",
 /*   8 */ "conditionalformat ::= LESSEQUAL expr",
 /*   9 */ "attribute ::=",
 /*  10 */ "table ::= tableid LABELSQUARE",
 /*  11 */ "expr ::= INTEGER",
 /*  12 */ "expr ::= FLOAT",
 /*  13 */ "expr ::= BOOL",
 /*  14 */ "expr ::= ERRORNAME attribute",
 /*  15 */ "expr ::= ERRORREF attribute",
 /*  16 */ "expr ::= SHEET ERRORREF attribute",
 /*  17 */ "expr ::= ID attribute",
 /*  18 */ "expr ::= ID CELL attribute",
 /*  19 */ "expr ::= SHEET ID attribute",
 /*  20 */ "expr ::= SHEET ID CELL attribute",
 /*  21 */ "expr ::= LABELSQ",
 /*  22 */ "expr ::= LABELDQ",
 /*  23 */ "expr ::= LABELSQUARE",
 /*  24 */ "thisrowcol ::= AT LABELSQUARE",
 /*  25 */ "thisrowcol ::= AT ID",
 /*  26 */ "expr ::= CELL attribute",
 /*  27 */ "expr ::= SHEET CELL attribute",
 /*  28 */ "expr ::= CELL HASH",
 /*  29 */ "expr ::= SHEET CELL HASH",
 /*  30 */ "expr ::= CELL COLON CELL",
 /*  31 */ "expr ::= ERRORREF COLON ID",
 /*  32 */ "expr ::= ERRORREF COLON CELL",
 /*  33 */ "expr ::= ERRORREF COLON ERRORREF",
 /*  34 */ "expr ::= CELL COLON ERRORREF",
 /*  35 */ "expr ::= CELL COLON ID",
 /*  36 */ "expr ::= ID COLON CELL",
 /*  37 */ "expr ::= ID COLON ID",
 /*  38 */ "expr ::= ID COLON ERRORREF",
 /*  39 */ "expr ::= SHEET CELL COLON CELL",
 /*  40 */ "expr ::= CELL COLON funcBegin funcEnd",
 /*  41 */ "expr ::= funcBegin funcEnd COLON CELL",
 /*  42 */ "expr ::= funcBegin funcEnd COLON funcBegin funcEnd",
 /*  43 */ "expr ::= table COLON funcBegin funcEnd",
 /*  44 */ "expr ::= funcBegin funcEnd COLON table",
 /*  45 */ "expr ::= table COLON table",
 /*  46 */ "expr ::= MINUS expr",
 /*  47 */ "expr ::= PLUS expr",
 /*  48 */ "expr ::= expr PERCENT",
 /*  49 */ "expr ::= expr TIMES expr",
 /*  50 */ "expr ::= expr DIVIDE expr",
 /*  51 */ "expr ::= expr MINUS expr",
 /*  52 */ "expr ::= expr PLUS expr",
 /*  53 */ "expr ::= expr AMPERSAND expr",
 /*  54 */ "expr ::= expr EQUAL expr",
 /*  55 */ "expr ::= expr NOTEQUAL expr",
 /*  56 */ "expr ::= expr GREATER expr",
 /*  57 */ "expr ::= expr GREATEREQUAL expr",
 /*  58 */ "expr ::= expr LESS expr",
 /*  59 */ "expr ::= expr LESSEQUAL expr",
 /*  60 */ "expr ::= LEFTPARENT expr RIGHTPARENT",
 /*  61 */ "listcell ::= INTEGER",
 /*  62 */ "listcell ::= FLOAT",
 /*  63 */ "listcell ::= BOOL",
 /*  64 */ "listcell ::= LABELSQ",
 /*  65 */ "listcell ::= LABELDQ",
 /*  66 */ "listcell ::= MINUS INTEGER",
 /*  67 */ "listcell ::= MINUS FLOAT",
 /*  68 */ "listcell ::= PLUS INTEGER",
 /*  69 */ "listcell ::= PLUS FLOAT",
 /*  70 */ "listcomma ::= listliteral COMMA",
 /*  71 */ "listsemi ::= listliteral SEMICOLON",
 /*  72 */ "openbrace ::= LEFTCURLY",
 /*  73 */ "openpipe ::= PIPE",
 /*  74 */ "expr ::= openbrace listliteral RIGHTCURLY",
 /*  75 */ "expr ::= openpipe listliteral PIPE",
 /*  76 */ "exprList ::= expr",
 /*  77 */ "exprList ::= exprList argsep expr",
 /*  78 */ "exprList ::= exprList argsep",
 /*  79 */ "funcBegin ::= ID LEFTPARENT",
 /*  80 */ "funcEnd ::= exprList RIGHTPARENT",
 /*  81 */ "expr ::= funcBegin funcEnd",
 /*  82 */ "letBegin ::= LET LEFTPARENT",
 /*  83 */ "letBinding ::= ID argsep expr",
 /*  84 */ "expr ::= letBegin letBindings argsep expr RIGHTPARENT",
 /*  85 */ "main ::= in",
 /*  86 */ "in ::=",
 /*  87 */ "state ::= percent_prefix conditionalformat",
 /*  88 */ "attribute ::= ATTRIBUTE",
 /*  89 */ "tableid ::= ID",
 /*  90 */ "tableid ::= LABELSQ",
 /*  91 */ "tableid ::= LABELDQ",
 /*  92 */ "expr ::= table",
 /*  93 */ "expr ::= thisrowcol",
 /*  94 */ "listliteral ::=",
 /*  95 */ "listliteral ::= listcell",
 /*  96 */ "listliteral ::= listcomma listcell",
 /*  97 */ "listliteral ::= listsemi listcell",
 /*  98 */ "argsep ::= COMMA",
 /*  99 */ "argsep ::= SEMICOLON",
 /* 100 */ "exprList ::=",
 /* 101 */ "letBindings ::= letBinding",
 /* 102 */ "letBindings ::= letBindings argsep letBinding",
};
#endif /* NDEBUG */


#if YYSTACKDEPTH<=0
/*
** Try to increase the size of the parser stack.  Return the number
** of errors.  Return 0 on success.
*/
static int yyGrowStack(yyParser *p){
  int newSize;
  int idx;
  yyStackEntry *pNew;

  newSize = p->yystksz*2 + 100;
  idx = p->yytos ? (int)(p->yytos - p->yystack) : 0;
  if( p->yystack==&p->yystk0 ){
    pNew = malloc(newSize*sizeof(pNew[0]));
    if( pNew ) pNew[0] = p->yystk0;
  }else{
    pNew = realloc(p->yystack, newSize*sizeof(pNew[0]));
  }
  if( pNew ){
    p->yystack = pNew;
    p->yytos = &p->yystack[idx];
#ifndef NDEBUG
    if( yyTraceFILE ){
      fprintf(yyTraceFILE,"%sStack grows from %d to %d entries.\n",
              yyTracePrompt, p->yystksz, newSize);
    }
#endif
    p->yystksz = newSize;
  }
  return pNew==0; 
}
#endif

/* Datatype of the argument to the memory allocated passed as the
** second argument to ParseAlloc() below.  This can be changed by
** putting an appropriate #define in the %include section of the input
** grammar.
*/
#ifndef YYMALLOCARGTYPE
# define YYMALLOCARGTYPE size_t
#endif

/* Initialize a new parser that has already been allocated.
*/
void ParseInit(void *yypRawParser ParseCTX_PDECL){
  yyParser *yypParser = (yyParser*)yypRawParser;
  ParseCTX_STORE
#ifdef YYTRACKMAXSTACKDEPTH
  yypParser->yyhwm = 0;
#endif
#if YYSTACKDEPTH<=0
  yypParser->yytos = NULL;
  yypParser->yystack = NULL;
  yypParser->yystksz = 0;
  if( yyGrowStack(yypParser) ){
    yypParser->yystack = &yypParser->yystk0;
    yypParser->yystksz = 1;
  }
#endif
#ifndef YYNOERRORRECOVERY
  yypParser->yyerrcnt = -1;
#endif
  yypParser->yytos = yypParser->yystack;
  yypParser->yystack[0].stateno = 0;
  yypParser->yystack[0].major = 0;
#if YYSTACKDEPTH>0
  yypParser->yystackEnd = &yypParser->yystack[YYSTACKDEPTH-1];
#endif
}

#ifndef Parse_ENGINEALWAYSONSTACK
/* 
** This function allocates a new parser.
** The only argument is a pointer to a function which works like
** malloc.
**
** Inputs:
** A pointer to the function used to allocate memory.
**
** Outputs:
** A pointer to a parser.  This pointer is used in subsequent calls
** to Parse and ParseFree.
*/
void *ParseAlloc(void *(*mallocProc)(YYMALLOCARGTYPE) ParseCTX_PDECL){
  yyParser *yypParser;
  yypParser = (yyParser*)(*mallocProc)( (YYMALLOCARGTYPE)sizeof(yyParser) );
  if( yypParser ){
    ParseCTX_STORE
    ParseInit(yypParser ParseCTX_PARAM);
  }
  return (void*)yypParser;
}
#endif /* Parse_ENGINEALWAYSONSTACK */


/* The following function deletes the "minor type" or semantic value
** associated with a symbol.  The symbol can be either a terminal
** or nonterminal. "yymajor" is the symbol code, and "yypminor" is
** a pointer to the value to be deleted.  The code used to do the 
** deletions is derived from the %destructor and/or %token_destructor
** directives of the input grammar.
*/
static void yy_destructor(
  yyParser *yypParser,    /* The parser */
  YYCODETYPE yymajor,     /* Type code for object to destroy */
  YYMINORTYPE *yypminor   /* The object to be destroyed */
){
  ParseARG_FETCH
  ParseCTX_FETCH
#if defined(__linux__)
  (void)wInterface;
#endif
  switch( yymajor ){
    /* Here is inserted the actions which take place when a
    ** terminal or non-terminal is destroyed.  This can happen
    ** when the symbol is popped from the stack during a
    ** reduce or during error processing or when a parser is 
    ** being destroyed before it is finished parsing.
    **
    ** Note: during a reduce, the only symbols destroyed are those
    ** which appear on the RHS of the rule, but which are *not* used
    ** inside the C code.
    */
/********* Begin destructor definitions ***************************************/
      /* TERMINAL Destructor */
    case 1: /* ID */
    case 2: /* LABELDQ */
    case 3: /* LABELSQ */
    case 4: /* LABELSQUARE */
    case 5: /* CELL */
    case 6: /* ATTRIBUTE */
    case 7: /* ERRORREF */
    case 8: /* ERRORNAME */
    case 9: /* PERCENT */
    case 10: /* AT */
    case 11: /* HASH */
    case 12: /* EQUAL */
    case 13: /* NOTEQUAL */
    case 14: /* GREATER */
    case 15: /* GREATEREQUAL */
    case 16: /* LESS */
    case 17: /* LESSEQUAL */
    case 18: /* AMPERSAND */
    case 19: /* PLUS */
    case 20: /* MINUS */
    case 21: /* TIMES */
    case 22: /* DIVIDE */
    case 23: /* MOD */
    case 24: /* COMMA */
    case 25: /* SEMICOLON */
    case 26: /* PIPE */
    case 27: /* LEFTSQUARE */
    case 28: /* LEFTPARENT */
    case 29: /* RIGHTSQUARE */
    case 30: /* RIGHTPARENT */
    case 31: /* LEFTCURLY */
    case 32: /* RIGHTCURLY */
    case 33: /* END */
    case 34: /* INTEGER */
    case 35: /* FLOAT */
    case 36: /* BOOL */
    case 37: /* SHEET */
    case 38: /* COLON */
    case 39: /* LET */
{
 token_destructor((yypminor->yy0)); 
}
      break;
/********* End destructor definitions *****************************************/
    default:  break;   /* If no destructor action specified: do nothing */
  }
}

/*
** Pop the parser's stack once.
**
** If there is a destructor routine associated with the token which
** is popped from the stack, then call it.
*/
static void yy_pop_parser_stack(yyParser *pParser){
  yyStackEntry *yytos;
  assert( pParser->yytos!=0 );
  assert( pParser->yytos > pParser->yystack );
  yytos = pParser->yytos--;
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sPopping %s\n",
      yyTracePrompt,
      yyTokenName[yytos->major]);
  }
#endif
  yy_destructor(pParser, yytos->major, &yytos->minor);
}

/*
** Clear all secondary memory allocations from the parser
*/
void ParseFinalize(void *p){
  yyParser *pParser = (yyParser*)p;
  while( pParser->yytos>pParser->yystack ) yy_pop_parser_stack(pParser);
#if YYSTACKDEPTH<=0
  if( pParser->yystack!=&pParser->yystk0 ) free(pParser->yystack);
#endif
}

#ifndef Parse_ENGINEALWAYSONSTACK
/* 
** Deallocate and destroy a parser.  Destructors are called for
** all stack elements before shutting the parser down.
**
** If the YYPARSEFREENEVERNULL macro exists (for example because it
** is defined in a %include section of the input grammar) then it is
** assumed that the input pointer is never NULL.
*/
void ParseFree(
  void *p,                    /* The parser to be deleted */
  void (*freeProc)(void*)     /* Function used to reclaim memory */
){
#ifndef YYPARSEFREENEVERNULL
  if( p==0 ) return;
#endif
  ParseFinalize(p);
  (*freeProc)(p);
}
#endif /* Parse_ENGINEALWAYSONSTACK */

/*
** Return the peak depth of the stack for a parser.
*/
#ifdef YYTRACKMAXSTACKDEPTH
int ParseStackPeak(void *p){
  yyParser *pParser = (yyParser*)p;
  return pParser->yyhwm;
}
#endif

/* This array of booleans keeps track of the parser statement
** coverage.  The element yycoverage[X][Y] is set when the parser
** is in state X and has a lookahead token Y.  In a well-tested
** systems, every element of this matrix should end up being set.
*/
#if defined(YYCOVERAGE)
static unsigned char yycoverage[YYNSTATE][YYNTOKEN];
#endif

/*
** Write into out a description of every state/lookahead combination that
**
**   (1)  has not been used by the parser, and
**   (2)  is not a syntax error.
**
** Return the number of missed state/lookahead combinations.
*/
#if defined(YYCOVERAGE)
int ParseCoverage(FILE *out){
  int stateno, iLookAhead, i;
  int nMissed = 0;
  for(stateno=0; stateno<YYNSTATE; stateno++){
    i = yy_shift_ofst[stateno];
    for(iLookAhead=0; iLookAhead<YYNTOKEN; iLookAhead++){
      if( yy_lookahead[i+iLookAhead]!=iLookAhead ) continue;
      if( yycoverage[stateno][iLookAhead]==0 ) nMissed++;
      if( out ){
        fprintf(out,"State %d lookahead %s %s\n", stateno,
                yyTokenName[iLookAhead],
                yycoverage[stateno][iLookAhead] ? "ok" : "missed");
      }
    }
  }
  return nMissed;
}
#endif

/*
** Find the appropriate action for a parser given the terminal
** look-ahead token iLookAhead.
*/
static YYACTIONTYPE yy_find_shift_action(
  YYCODETYPE iLookAhead,    /* The look-ahead token */
  YYACTIONTYPE stateno      /* Current state number */
){
  int i;

  if( stateno>YY_MAX_SHIFT ) return stateno;
  assert( stateno <= YY_SHIFT_COUNT );
#if defined(YYCOVERAGE)
  yycoverage[stateno][iLookAhead] = 1;
#endif
  do{
    i = yy_shift_ofst[stateno];
    assert( i>=0 );
    assert( i<=YY_ACTTAB_COUNT );
    assert( i+YYNTOKEN<=(int)YY_NLOOKAHEAD );
    assert( iLookAhead!=YYNOCODE );
    assert( iLookAhead < YYNTOKEN );
    i += iLookAhead;
    assert( i<(int)YY_NLOOKAHEAD );
    if( yy_lookahead[i]!=iLookAhead ){
#ifdef YYFALLBACK
      YYCODETYPE iFallback;            /* Fallback token */
      assert( iLookAhead<sizeof(yyFallback)/sizeof(yyFallback[0]) );
      iFallback = yyFallback[iLookAhead];
      if( iFallback!=0 ){
#ifndef NDEBUG
        if( yyTraceFILE ){
          fprintf(yyTraceFILE, "%sFALLBACK %s => %s\n",
             yyTracePrompt, yyTokenName[iLookAhead], yyTokenName[iFallback]);
        }
#endif
        assert( yyFallback[iFallback]==0 ); /* Fallback loop must terminate */
        iLookAhead = iFallback;
        continue;
      }
#endif
#ifdef YYWILDCARD
      {
        int j = i - iLookAhead + YYWILDCARD;
        assert( j<(int)(sizeof(yy_lookahead)/sizeof(yy_lookahead[0])) );
        if( yy_lookahead[j]==YYWILDCARD && iLookAhead>0 ){
#ifndef NDEBUG
          if( yyTraceFILE ){
            fprintf(yyTraceFILE, "%sWILDCARD %s => %s\n",
               yyTracePrompt, yyTokenName[iLookAhead],
               yyTokenName[YYWILDCARD]);
          }
#endif /* NDEBUG */
          return yy_action[j];
        }
      }
#endif /* YYWILDCARD */
      return yy_default[stateno];
    }else{
      assert( i>=0 && i<(int)(sizeof(yy_action)/sizeof(yy_action[0])) );
      return yy_action[i];
    }
  }while(1);
}

/*
** Find the appropriate action for a parser given the non-terminal
** look-ahead token iLookAhead.
*/
static YYACTIONTYPE yy_find_reduce_action(
  YYACTIONTYPE stateno,     /* Current state number */
  YYCODETYPE iLookAhead     /* The look-ahead token */
){
  int i;
#ifdef YYERRORSYMBOL
  if( stateno>YY_REDUCE_COUNT ){
    return yy_default[stateno];
  }
#else
  assert( stateno<=YY_REDUCE_COUNT );
#endif
  i = yy_reduce_ofst[stateno];
  assert( iLookAhead!=YYNOCODE );
  i += iLookAhead;
#ifdef YYERRORSYMBOL
  if( i<0 || i>=YY_ACTTAB_COUNT || yy_lookahead[i]!=iLookAhead ){
    return yy_default[stateno];
  }
#else
  assert( i>=0 && i<YY_ACTTAB_COUNT );
  assert( yy_lookahead[i]==iLookAhead );
#endif
  return yy_action[i];
}

/*
** The following routine is called if the stack overflows.
*/
static void yyStackOverflow(yyParser *yypParser){
   ParseARG_FETCH
   ParseCTX_FETCH
#ifndef NDEBUG
   if( yyTraceFILE ){
     fprintf(yyTraceFILE,"%sStack Overflow!\n",yyTracePrompt);
   }
#endif
   while( yypParser->yytos>yypParser->yystack ) yy_pop_parser_stack(yypParser);
   /* Here code is inserted which will execute if the parser
   ** stack every overflows */
/******** Begin %stack_overflow code ******************************************/
/******** End %stack_overflow code ********************************************/
   ParseARG_STORE /* Suppress warning about unused %extra_argument var */
   ParseCTX_STORE
}

/*
** Print tracing information for a SHIFT action
*/
#ifndef NDEBUG
static void yyTraceShift(yyParser *yypParser, int yyNewState, const char *zTag){
  if( yyTraceFILE ){
    if( yyNewState<YYNSTATE ){
      fprintf(yyTraceFILE,"%s%s '%s', go to state %d\n",
         yyTracePrompt, zTag, yyTokenName[yypParser->yytos->major],
         yyNewState);
    }else{
      fprintf(yyTraceFILE,"%s%s '%s', pending reduce %d\n",
         yyTracePrompt, zTag, yyTokenName[yypParser->yytos->major],
         yyNewState - YY_MIN_REDUCE);
    }
  }
}
#else
# define yyTraceShift(X,Y,Z)
#endif

/*
** Perform a shift action.
*/
static void yy_shift(
  yyParser *yypParser,          /* The parser to be shifted */
  YYACTIONTYPE yyNewState,      /* The new state to shift in */
  YYCODETYPE yyMajor,           /* The major token to shift in */
  ParseTOKENTYPE yyMinor        /* The minor token to shift in */
){
  yyStackEntry *yytos;
  yypParser->yytos++;
#ifdef YYTRACKMAXSTACKDEPTH
  if( (int)(yypParser->yytos - yypParser->yystack)>yypParser->yyhwm ){
    yypParser->yyhwm++;
    assert( yypParser->yyhwm == (int)(yypParser->yytos - yypParser->yystack) );
  }
#endif
#if YYSTACKDEPTH>0 
  if( yypParser->yytos>yypParser->yystackEnd ){
    yypParser->yytos--;
    yyStackOverflow(yypParser);
    return;
  }
#else
  if( yypParser->yytos>=&yypParser->yystack[yypParser->yystksz] ){
    if( yyGrowStack(yypParser) ){
      yypParser->yytos--;
      yyStackOverflow(yypParser);
      return;
    }
  }
#endif
  if( yyNewState > YY_MAX_SHIFT ){
    yyNewState += YY_MIN_REDUCE - YY_MIN_SHIFTREDUCE;
  }
  yytos = yypParser->yytos;
  yytos->stateno = yyNewState;
  yytos->major = yyMajor;
  yytos->minor.yy0 = yyMinor;
  yyTraceShift(yypParser, yyNewState, "Shift");
}

/* For rule J, yyRuleInfoLhs[J] contains the symbol on the left-hand side
** of that rule */
static const YYCODETYPE yyRuleInfoLhs[] = {
    46,  /* (0) in ::= in state END */
    47,  /* (1) state ::= expr */
    48,  /* (2) percent_prefix ::= PERCENT */
    49,  /* (3) conditionalformat ::= EQUAL expr */
    49,  /* (4) conditionalformat ::= NOTEQUAL expr */
    49,  /* (5) conditionalformat ::= GREATER expr */
    49,  /* (6) conditionalformat ::= GREATEREQUAL expr */
    49,  /* (7) conditionalformat ::= LESS expr */
    49,  /* (8) conditionalformat ::= LESSEQUAL expr */
    41,  /* (9) attribute ::= */
    50,  /* (10) table ::= tableid LABELSQUARE */
    40,  /* (11) expr ::= INTEGER */
    40,  /* (12) expr ::= FLOAT */
    40,  /* (13) expr ::= BOOL */
    40,  /* (14) expr ::= ERRORNAME attribute */
    40,  /* (15) expr ::= ERRORREF attribute */
    40,  /* (16) expr ::= SHEET ERRORREF attribute */
    40,  /* (17) expr ::= ID attribute */
    40,  /* (18) expr ::= ID CELL attribute */
    40,  /* (19) expr ::= SHEET ID attribute */
    40,  /* (20) expr ::= SHEET ID CELL attribute */
    40,  /* (21) expr ::= LABELSQ */
    40,  /* (22) expr ::= LABELDQ */
    40,  /* (23) expr ::= LABELSQUARE */
    44,  /* (24) thisrowcol ::= AT LABELSQUARE */
    44,  /* (25) thisrowcol ::= AT ID */
    40,  /* (26) expr ::= CELL attribute */
    40,  /* (27) expr ::= SHEET CELL attribute */
    40,  /* (28) expr ::= CELL HASH */
    40,  /* (29) expr ::= SHEET CELL HASH */
    40,  /* (30) expr ::= CELL COLON CELL */
    40,  /* (31) expr ::= ERRORREF COLON ID */
    40,  /* (32) expr ::= ERRORREF COLON CELL */
    40,  /* (33) expr ::= ERRORREF COLON ERRORREF */
    40,  /* (34) expr ::= CELL COLON ERRORREF */
    40,  /* (35) expr ::= CELL COLON ID */
    40,  /* (36) expr ::= ID COLON CELL */
    40,  /* (37) expr ::= ID COLON ID */
    40,  /* (38) expr ::= ID COLON ERRORREF */
    40,  /* (39) expr ::= SHEET CELL COLON CELL */
    40,  /* (40) expr ::= CELL COLON funcBegin funcEnd */
    40,  /* (41) expr ::= funcBegin funcEnd COLON CELL */
    40,  /* (42) expr ::= funcBegin funcEnd COLON funcBegin funcEnd */
    40,  /* (43) expr ::= table COLON funcBegin funcEnd */
    40,  /* (44) expr ::= funcBegin funcEnd COLON table */
    40,  /* (45) expr ::= table COLON table */
    40,  /* (46) expr ::= MINUS expr */
    40,  /* (47) expr ::= PLUS expr */
    40,  /* (48) expr ::= expr PERCENT */
    40,  /* (49) expr ::= expr TIMES expr */
    40,  /* (50) expr ::= expr DIVIDE expr */
    40,  /* (51) expr ::= expr MINUS expr */
    40,  /* (52) expr ::= expr PLUS expr */
    40,  /* (53) expr ::= expr AMPERSAND expr */
    40,  /* (54) expr ::= expr EQUAL expr */
    40,  /* (55) expr ::= expr NOTEQUAL expr */
    40,  /* (56) expr ::= expr GREATER expr */
    40,  /* (57) expr ::= expr GREATEREQUAL expr */
    40,  /* (58) expr ::= expr LESS expr */
    40,  /* (59) expr ::= expr LESSEQUAL expr */
    40,  /* (60) expr ::= LEFTPARENT expr RIGHTPARENT */
    53,  /* (61) listcell ::= INTEGER */
    53,  /* (62) listcell ::= FLOAT */
    53,  /* (63) listcell ::= BOOL */
    53,  /* (64) listcell ::= LABELSQ */
    53,  /* (65) listcell ::= LABELDQ */
    53,  /* (66) listcell ::= MINUS INTEGER */
    53,  /* (67) listcell ::= MINUS FLOAT */
    53,  /* (68) listcell ::= PLUS INTEGER */
    53,  /* (69) listcell ::= PLUS FLOAT */
    54,  /* (70) listcomma ::= listliteral COMMA */
    56,  /* (71) listsemi ::= listliteral SEMICOLON */
    57,  /* (72) openbrace ::= LEFTCURLY */
    58,  /* (73) openpipe ::= PIPE */
    40,  /* (74) expr ::= openbrace listliteral RIGHTCURLY */
    40,  /* (75) expr ::= openpipe listliteral PIPE */
    60,  /* (76) exprList ::= expr */
    60,  /* (77) exprList ::= exprList argsep expr */
    60,  /* (78) exprList ::= exprList argsep */
    51,  /* (79) funcBegin ::= ID LEFTPARENT */
    52,  /* (80) funcEnd ::= exprList RIGHTPARENT */
    40,  /* (81) expr ::= funcBegin funcEnd */
    61,  /* (82) letBegin ::= LET LEFTPARENT */
    62,  /* (83) letBinding ::= ID argsep expr */
    40,  /* (84) expr ::= letBegin letBindings argsep expr RIGHTPARENT */
    45,  /* (85) main ::= in */
    46,  /* (86) in ::= */
    47,  /* (87) state ::= percent_prefix conditionalformat */
    41,  /* (88) attribute ::= ATTRIBUTE */
    42,  /* (89) tableid ::= ID */
    42,  /* (90) tableid ::= LABELSQ */
    42,  /* (91) tableid ::= LABELDQ */
    40,  /* (92) expr ::= table */
    40,  /* (93) expr ::= thisrowcol */
    55,  /* (94) listliteral ::= */
    55,  /* (95) listliteral ::= listcell */
    55,  /* (96) listliteral ::= listcomma listcell */
    55,  /* (97) listliteral ::= listsemi listcell */
    59,  /* (98) argsep ::= COMMA */
    59,  /* (99) argsep ::= SEMICOLON */
    60,  /* (100) exprList ::= */
    63,  /* (101) letBindings ::= letBinding */
    63,  /* (102) letBindings ::= letBindings argsep letBinding */
};

/* For rule J, yyRuleInfoNRhs[J] contains the negative of the number
** of symbols on the right-hand side of that rule. */
static const signed char yyRuleInfoNRhs[] = {
   -3,  /* (0) in ::= in state END */
   -1,  /* (1) state ::= expr */
   -1,  /* (2) percent_prefix ::= PERCENT */
   -2,  /* (3) conditionalformat ::= EQUAL expr */
   -2,  /* (4) conditionalformat ::= NOTEQUAL expr */
   -2,  /* (5) conditionalformat ::= GREATER expr */
   -2,  /* (6) conditionalformat ::= GREATEREQUAL expr */
   -2,  /* (7) conditionalformat ::= LESS expr */
   -2,  /* (8) conditionalformat ::= LESSEQUAL expr */
    0,  /* (9) attribute ::= */
   -2,  /* (10) table ::= tableid LABELSQUARE */
   -1,  /* (11) expr ::= INTEGER */
   -1,  /* (12) expr ::= FLOAT */
   -1,  /* (13) expr ::= BOOL */
   -2,  /* (14) expr ::= ERRORNAME attribute */
   -2,  /* (15) expr ::= ERRORREF attribute */
   -3,  /* (16) expr ::= SHEET ERRORREF attribute */
   -2,  /* (17) expr ::= ID attribute */
   -3,  /* (18) expr ::= ID CELL attribute */
   -3,  /* (19) expr ::= SHEET ID attribute */
   -4,  /* (20) expr ::= SHEET ID CELL attribute */
   -1,  /* (21) expr ::= LABELSQ */
   -1,  /* (22) expr ::= LABELDQ */
   -1,  /* (23) expr ::= LABELSQUARE */
   -2,  /* (24) thisrowcol ::= AT LABELSQUARE */
   -2,  /* (25) thisrowcol ::= AT ID */
   -2,  /* (26) expr ::= CELL attribute */
   -3,  /* (27) expr ::= SHEET CELL attribute */
   -2,  /* (28) expr ::= CELL HASH */
   -3,  /* (29) expr ::= SHEET CELL HASH */
   -3,  /* (30) expr ::= CELL COLON CELL */
   -3,  /* (31) expr ::= ERRORREF COLON ID */
   -3,  /* (32) expr ::= ERRORREF COLON CELL */
   -3,  /* (33) expr ::= ERRORREF COLON ERRORREF */
   -3,  /* (34) expr ::= CELL COLON ERRORREF */
   -3,  /* (35) expr ::= CELL COLON ID */
   -3,  /* (36) expr ::= ID COLON CELL */
   -3,  /* (37) expr ::= ID COLON ID */
   -3,  /* (38) expr ::= ID COLON ERRORREF */
   -4,  /* (39) expr ::= SHEET CELL COLON CELL */
   -4,  /* (40) expr ::= CELL COLON funcBegin funcEnd */
   -4,  /* (41) expr ::= funcBegin funcEnd COLON CELL */
   -5,  /* (42) expr ::= funcBegin funcEnd COLON funcBegin funcEnd */
   -4,  /* (43) expr ::= table COLON funcBegin funcEnd */
   -4,  /* (44) expr ::= funcBegin funcEnd COLON table */
   -3,  /* (45) expr ::= table COLON table */
   -2,  /* (46) expr ::= MINUS expr */
   -2,  /* (47) expr ::= PLUS expr */
   -2,  /* (48) expr ::= expr PERCENT */
   -3,  /* (49) expr ::= expr TIMES expr */
   -3,  /* (50) expr ::= expr DIVIDE expr */
   -3,  /* (51) expr ::= expr MINUS expr */
   -3,  /* (52) expr ::= expr PLUS expr */
   -3,  /* (53) expr ::= expr AMPERSAND expr */
   -3,  /* (54) expr ::= expr EQUAL expr */
   -3,  /* (55) expr ::= expr NOTEQUAL expr */
   -3,  /* (56) expr ::= expr GREATER expr */
   -3,  /* (57) expr ::= expr GREATEREQUAL expr */
   -3,  /* (58) expr ::= expr LESS expr */
   -3,  /* (59) expr ::= expr LESSEQUAL expr */
   -3,  /* (60) expr ::= LEFTPARENT expr RIGHTPARENT */
   -1,  /* (61) listcell ::= INTEGER */
   -1,  /* (62) listcell ::= FLOAT */
   -1,  /* (63) listcell ::= BOOL */
   -1,  /* (64) listcell ::= LABELSQ */
   -1,  /* (65) listcell ::= LABELDQ */
   -2,  /* (66) listcell ::= MINUS INTEGER */
   -2,  /* (67) listcell ::= MINUS FLOAT */
   -2,  /* (68) listcell ::= PLUS INTEGER */
   -2,  /* (69) listcell ::= PLUS FLOAT */
   -2,  /* (70) listcomma ::= listliteral COMMA */
   -2,  /* (71) listsemi ::= listliteral SEMICOLON */
   -1,  /* (72) openbrace ::= LEFTCURLY */
   -1,  /* (73) openpipe ::= PIPE */
   -3,  /* (74) expr ::= openbrace listliteral RIGHTCURLY */
   -3,  /* (75) expr ::= openpipe listliteral PIPE */
   -1,  /* (76) exprList ::= expr */
   -3,  /* (77) exprList ::= exprList argsep expr */
   -2,  /* (78) exprList ::= exprList argsep */
   -2,  /* (79) funcBegin ::= ID LEFTPARENT */
   -2,  /* (80) funcEnd ::= exprList RIGHTPARENT */
   -2,  /* (81) expr ::= funcBegin funcEnd */
   -2,  /* (82) letBegin ::= LET LEFTPARENT */
   -3,  /* (83) letBinding ::= ID argsep expr */
   -5,  /* (84) expr ::= letBegin letBindings argsep expr RIGHTPARENT */
   -1,  /* (85) main ::= in */
    0,  /* (86) in ::= */
   -2,  /* (87) state ::= percent_prefix conditionalformat */
   -1,  /* (88) attribute ::= ATTRIBUTE */
   -1,  /* (89) tableid ::= ID */
   -1,  /* (90) tableid ::= LABELSQ */
   -1,  /* (91) tableid ::= LABELDQ */
   -1,  /* (92) expr ::= table */
   -1,  /* (93) expr ::= thisrowcol */
    0,  /* (94) listliteral ::= */
   -1,  /* (95) listliteral ::= listcell */
   -2,  /* (96) listliteral ::= listcomma listcell */
   -2,  /* (97) listliteral ::= listsemi listcell */
   -1,  /* (98) argsep ::= COMMA */
   -1,  /* (99) argsep ::= SEMICOLON */
    0,  /* (100) exprList ::= */
   -1,  /* (101) letBindings ::= letBinding */
   -3,  /* (102) letBindings ::= letBindings argsep letBinding */
};

static void yy_accept(yyParser*);  /* Forward Declaration */

/*
** Perform a reduce action and the shift that must immediately
** follow the reduce.
**
** The yyLookahead and yyLookaheadToken parameters provide reduce actions
** access to the lookahead token (if any).  The yyLookahead will be YYNOCODE
** if the lookahead token has already been consumed.  As this procedure is
** only called from one place, optimizing compilers will in-line it, which
** means that the extra parameters have no performance impact.
*/
static YYACTIONTYPE yy_reduce(
  yyParser *yypParser,         /* The parser */
  unsigned int yyruleno,       /* Number of the rule by which to reduce */
  int yyLookahead,             /* Lookahead token, or YYNOCODE if none */
  ParseTOKENTYPE yyLookaheadToken  /* Value of the lookahead token */
  ParseCTX_PDECL                   /* %extra_context */
){
  int yygoto;                     /* The next state */
  YYACTIONTYPE yyact;             /* The next action */
  yyStackEntry *yymsp;            /* The top of the parser's stack */
  int yysize;                     /* Amount to pop the stack */
  ParseARG_FETCH
  (void)yyLookahead;
  (void)yyLookaheadToken;
  yymsp = yypParser->yytos;
  assert( yyruleno<(int)(sizeof(yyRuleName)/sizeof(yyRuleName[0])) );
#ifndef NDEBUG
  if( yyTraceFILE ){
    yysize = yyRuleInfoNRhs[yyruleno];
    if( yysize ){
      fprintf(yyTraceFILE, "%sReduce %d [%s]%s, pop back to state %d.\n",
        yyTracePrompt,
        yyruleno, yyRuleName[yyruleno],
        yyruleno<YYNRULE_WITH_ACTION ? "" : " without external action",
        yymsp[yysize].stateno);
    }else{
      fprintf(yyTraceFILE, "%sReduce %d [%s]%s.\n",
        yyTracePrompt, yyruleno, yyRuleName[yyruleno],
        yyruleno<YYNRULE_WITH_ACTION ? "" : " without external action");
    }
  }
#endif /* NDEBUG */

  /* Check that the stack is large enough to grow by a single entry
  ** if the RHS of the rule is empty.  This ensures that there is room
  ** enough on the stack to push the LHS value */
  if( yyRuleInfoNRhs[yyruleno]==0 ){
#ifdef YYTRACKMAXSTACKDEPTH
    if( (int)(yypParser->yytos - yypParser->yystack)>yypParser->yyhwm ){
      yypParser->yyhwm++;
      assert( yypParser->yyhwm == (int)(yypParser->yytos - yypParser->yystack));
    }
#endif
#if YYSTACKDEPTH>0 
    if( yypParser->yytos>=yypParser->yystackEnd ){
      yyStackOverflow(yypParser);
      /* The call to yyStackOverflow() above pops the stack until it is
      ** empty, causing the main parser loop to exit.  So the return value
      ** is never used and does not matter. */
      return 0;
    }
#else
    if( yypParser->yytos>=&yypParser->yystack[yypParser->yystksz-1] ){
      if( yyGrowStack(yypParser) ){
        yyStackOverflow(yypParser);
        /* The call to yyStackOverflow() above pops the stack until it is
        ** empty, causing the main parser loop to exit.  So the return value
        ** is never used and does not matter. */
        return 0;
      }
      yymsp = yypParser->yytos;
    }
#endif
  }

  switch( yyruleno ){
  /* Beginning here are the reduction cases.  A typical example
  ** follows:
  **   case 0:
  **  #line <lineno> <grammarfile>
  **     { ... }           // User supplied code
  **  #line <lineno> <thisfile>
  **     break;
  */
/********** Begin reduce actions **********************************************/
      case 0: /* in ::= in state END */
{}
  yy_destructor(yypParser,33,&yymsp[0].minor);
        break;
      case 1: /* state ::= expr */
      case 81: /* expr ::= funcBegin funcEnd */ yytestcase(yyruleno==81);
{}
        break;
      case 2: /* percent_prefix ::= PERCENT */
{  yy_destructor(yypParser,9,&yymsp[0].minor);
{ wInterface->PushOp(tKind::Percent); }
}
        break;
      case 3: /* conditionalformat ::= EQUAL expr */
{  yy_destructor(yypParser,12,&yymsp[-1].minor);
{ wInterface->PushOp(tKind::Equal);  }
}
        break;
      case 4: /* conditionalformat ::= NOTEQUAL expr */
{  yy_destructor(yypParser,13,&yymsp[-1].minor);
{ wInterface->PushOp(tKind::NotEqual); }
}
        break;
      case 5: /* conditionalformat ::= GREATER expr */
{  yy_destructor(yypParser,14,&yymsp[-1].minor);
{ wInterface->PushOp(tKind::GreaterThan); }
}
        break;
      case 6: /* conditionalformat ::= GREATEREQUAL expr */
{  yy_destructor(yypParser,15,&yymsp[-1].minor);
{ wInterface->PushOp(tKind::GreaterThanOrEqual); }
}
        break;
      case 7: /* conditionalformat ::= LESS expr */
{  yy_destructor(yypParser,16,&yymsp[-1].minor);
{ wInterface->PushOp(tKind::LessThan); }
}
        break;
      case 8: /* conditionalformat ::= LESSEQUAL expr */
{  yy_destructor(yypParser,17,&yymsp[-1].minor);
{ wInterface->PushOp(tKind::LessThanOrEqual); }
}
        break;
      case 9: /* attribute ::= */
{ yymsp[1].minor.yy0.m_Token = nullptr; }
        break;
      case 10: /* table ::= tableid LABELSQUARE */
{ wInterface->PushTable(yymsp[-1].minor.yy0.m_Token,yymsp[0].minor.yy0.m_Token); }
        break;
      case 11: /* expr ::= INTEGER */
      case 61: /* listcell ::= INTEGER */ yytestcase(yyruleno==61);
{ wInterface->PushInteger(yymsp[0].minor.yy0.m_Token); }
        break;
      case 12: /* expr ::= FLOAT */
      case 62: /* listcell ::= FLOAT */ yytestcase(yyruleno==62);
{ wInterface->PushFloat(yymsp[0].minor.yy0.m_Token); }
        break;
      case 13: /* expr ::= BOOL */
      case 63: /* listcell ::= BOOL */ yytestcase(yyruleno==63);
{ wInterface->PushBool(yymsp[0].minor.yy0.m_Token); }
        break;
      case 14: /* expr ::= ERRORNAME attribute */
{ wInterface->PushErrorName(yymsp[-1].minor.yy0.m_Token); }
        break;
      case 15: /* expr ::= ERRORREF attribute */
{ wInterface->PushErrorRef(yymsp[-1].minor.yy0.m_Token); }
        break;
      case 16: /* expr ::= SHEET ERRORREF attribute */
{ wInterface->PushSheetErrorRef(yymsp[-2].minor.yy0.m_Token,yymsp[-1].minor.yy0.m_Token,yymsp[0].minor.yy0.m_Token); }
        break;
      case 17: /* expr ::= ID attribute */
{ wInterface->PushID(yymsp[-1].minor.yy0.m_Token,yymsp[0].minor.yy0.m_Token); }
        break;
      case 18: /* expr ::= ID CELL attribute */
{
  wInterface->PushNamedRangeR1C1OffsetParse(yymsp[-2].minor.yy0.m_Token, yymsp[-1].minor.yy0.m_Token, yymsp[0].minor.yy0.m_Token);
}
        break;
      case 19: /* expr ::= SHEET ID attribute */
{ wInterface->PushSheetID(yymsp[-2].minor.yy0.m_Token,yymsp[-1].minor.yy0.m_Token,yymsp[0].minor.yy0.m_Token); }
        break;
      case 20: /* expr ::= SHEET ID CELL attribute */
{
  wInterface->PushSheetNamedRangeR1C1OffsetParse(yymsp[-3].minor.yy0.m_Token, yymsp[-2].minor.yy0.m_Token, yymsp[-1].minor.yy0.m_Token, yymsp[0].minor.yy0.m_Token);
}
        break;
      case 21: /* expr ::= LABELSQ */
      case 22: /* expr ::= LABELDQ */ yytestcase(yyruleno==22);
      case 64: /* listcell ::= LABELSQ */ yytestcase(yyruleno==64);
      case 65: /* listcell ::= LABELDQ */ yytestcase(yyruleno==65);
{ wInterface->PushLabel(yymsp[0].minor.yy0.m_Token); }
        break;
      case 23: /* expr ::= LABELSQUARE */
{ wInterface->PushTable(nullptr,yymsp[0].minor.yy0.m_Token); }
        break;
      case 24: /* thisrowcol ::= AT LABELSQUARE */
      case 25: /* thisrowcol ::= AT ID */ yytestcase(yyruleno==25);
{  yy_destructor(yypParser,10,&yymsp[-1].minor);
{ wInterface->PushThisRowColumn(yymsp[0].minor.yy0.m_Token); }
}
        break;
      case 26: /* expr ::= CELL attribute */
{  wInterface->PushCell(yymsp[-1].minor.yy0.m_Token,yymsp[0].minor.yy0.m_Token); }
        break;
      case 27: /* expr ::= SHEET CELL attribute */
{  wInterface->PushSheetCell(yymsp[-2].minor.yy0.m_Token,yymsp[-1].minor.yy0.m_Token,yymsp[0].minor.yy0.m_Token); }
        break;
      case 28: /* expr ::= CELL HASH */
{ wInterface->PushSpillRef(yymsp[-1].minor.yy0.m_Token); }
  yy_destructor(yypParser,11,&yymsp[0].minor);
        break;
      case 29: /* expr ::= SHEET CELL HASH */
{ wInterface->PushSheetSpillRef(yymsp[-2].minor.yy0.m_Token, yymsp[-1].minor.yy0.m_Token); }
  yy_destructor(yypParser,11,&yymsp[0].minor);
        break;
      case 30: /* expr ::= CELL COLON CELL */
{  wInterface->PushRange(yymsp[-2].minor.yy0.m_Token,yymsp[0].minor.yy0.m_Token); }
  yy_destructor(yypParser,38,&yymsp[-1].minor);
        break;
      case 31: /* expr ::= ERRORREF COLON ID */
      case 32: /* expr ::= ERRORREF COLON CELL */ yytestcase(yyruleno==32);
      case 33: /* expr ::= ERRORREF COLON ERRORREF */ yytestcase(yyruleno==33);
      case 34: /* expr ::= CELL COLON ERRORREF */ yytestcase(yyruleno==34);
      case 35: /* expr ::= CELL COLON ID */ yytestcase(yyruleno==35);
      case 36: /* expr ::= ID COLON CELL */ yytestcase(yyruleno==36);
      case 37: /* expr ::= ID COLON ID */ yytestcase(yyruleno==37);
      case 38: /* expr ::= ID COLON ERRORREF */ yytestcase(yyruleno==38);
{ wInterface->PushRange(yymsp[-2].minor.yy0.m_Token, yymsp[0].minor.yy0.m_Token); }
  yy_destructor(yypParser,38,&yymsp[-1].minor);
        break;
      case 39: /* expr ::= SHEET CELL COLON CELL */
{ wInterface->PushSheetRange(yymsp[-3].minor.yy0.m_Token,yymsp[-2].minor.yy0.m_Token,yymsp[0].minor.yy0.m_Token); }
  yy_destructor(yypParser,38,&yymsp[-1].minor);
        break;
      case 40: /* expr ::= CELL COLON funcBegin funcEnd */
{ wInterface->PushDynamicRangeRight(yymsp[-3].minor.yy0.m_Token); }
  yy_destructor(yypParser,38,&yymsp[-2].minor);
        break;
      case 41: /* expr ::= funcBegin funcEnd COLON CELL */
{ wInterface->PushDynamicRangeLeft(yymsp[0].minor.yy0.m_Token); }
  yy_destructor(yypParser,38,&yymsp[-1].minor);
        break;
      case 42: /* expr ::= funcBegin funcEnd COLON funcBegin funcEnd */
      case 43: /* expr ::= table COLON funcBegin funcEnd */ yytestcase(yyruleno==43);
{ wInterface->PushDynamicRangeBoth(); }
  yy_destructor(yypParser,38,&yymsp[-2].minor);
        break;
      case 44: /* expr ::= funcBegin funcEnd COLON table */
      case 45: /* expr ::= table COLON table */ yytestcase(yyruleno==45);
{ wInterface->PushDynamicRangeBoth(); }
  yy_destructor(yypParser,38,&yymsp[-1].minor);
        break;
      case 46: /* expr ::= MINUS expr */
{  yy_destructor(yypParser,20,&yymsp[-1].minor);
{  wInterface->PushOp(tKind::UnaryMinus); }
}
        break;
      case 47: /* expr ::= PLUS expr */
{  yy_destructor(yypParser,19,&yymsp[-1].minor);
{ /* Excel unary plus: identity, no bytecode */ }
}
        break;
      case 48: /* expr ::= expr PERCENT */
{ wInterface->PushPercentLiteral(); }
  yy_destructor(yypParser,9,&yymsp[0].minor);
        break;
      case 49: /* expr ::= expr TIMES expr */
{ wInterface->PushOp(tKind::Times); }
  yy_destructor(yypParser,21,&yymsp[-1].minor);
        break;
      case 50: /* expr ::= expr DIVIDE expr */
{ wInterface->PushOp(tKind::Divide); }
  yy_destructor(yypParser,22,&yymsp[-1].minor);
        break;
      case 51: /* expr ::= expr MINUS expr */
{ wInterface->PushOp(tKind::Minus); }
  yy_destructor(yypParser,20,&yymsp[-1].minor);
        break;
      case 52: /* expr ::= expr PLUS expr */
{ wInterface->PushOp(tKind::Plus); }
  yy_destructor(yypParser,19,&yymsp[-1].minor);
        break;
      case 53: /* expr ::= expr AMPERSAND expr */
{ wInterface->PushOp(tKind::Ampersand); }
  yy_destructor(yypParser,18,&yymsp[-1].minor);
        break;
      case 54: /* expr ::= expr EQUAL expr */
{ wInterface->PushOp(tKind::Equal); }
  yy_destructor(yypParser,12,&yymsp[-1].minor);
        break;
      case 55: /* expr ::= expr NOTEQUAL expr */
{ wInterface->PushOp(tKind::NotEqual); }
  yy_destructor(yypParser,13,&yymsp[-1].minor);
        break;
      case 56: /* expr ::= expr GREATER expr */
{ wInterface->PushOp(tKind::GreaterThan); }
  yy_destructor(yypParser,14,&yymsp[-1].minor);
        break;
      case 57: /* expr ::= expr GREATEREQUAL expr */
{ wInterface->PushOp(tKind::GreaterThanOrEqual); }
  yy_destructor(yypParser,15,&yymsp[-1].minor);
        break;
      case 58: /* expr ::= expr LESS expr */
{ wInterface->PushOp(tKind::LessThan); }
  yy_destructor(yypParser,16,&yymsp[-1].minor);
        break;
      case 59: /* expr ::= expr LESSEQUAL expr */
{ wInterface->PushOp(tKind::LessThanOrEqual); }
  yy_destructor(yypParser,17,&yymsp[-1].minor);
        break;
      case 60: /* expr ::= LEFTPARENT expr RIGHTPARENT */
{  yy_destructor(yypParser,28,&yymsp[-2].minor);
{}
  yy_destructor(yypParser,30,&yymsp[0].minor);
}
        break;
      case 66: /* listcell ::= MINUS INTEGER */
{  yy_destructor(yypParser,20,&yymsp[-1].minor);
{ wInterface->PushInteger(yymsp[0].minor.yy0.m_Token, true); }
}
        break;
      case 67: /* listcell ::= MINUS FLOAT */
{  yy_destructor(yypParser,20,&yymsp[-1].minor);
{ wInterface->PushFloat(yymsp[0].minor.yy0.m_Token, true); }
}
        break;
      case 68: /* listcell ::= PLUS INTEGER */
{  yy_destructor(yypParser,19,&yymsp[-1].minor);
{ wInterface->PushInteger(yymsp[0].minor.yy0.m_Token); }
}
        break;
      case 69: /* listcell ::= PLUS FLOAT */
{  yy_destructor(yypParser,19,&yymsp[-1].minor);
{ wInterface->PushFloat(yymsp[0].minor.yy0.m_Token); }
}
        break;
      case 70: /* listcomma ::= listliteral COMMA */
{ wInterface->PushOp(tKind::Comma); }
  yy_destructor(yypParser,24,&yymsp[0].minor);
        break;
      case 71: /* listsemi ::= listliteral SEMICOLON */
{ wInterface->PushOp(tKind::Semicolon); }
  yy_destructor(yypParser,25,&yymsp[0].minor);
        break;
      case 72: /* openbrace ::= LEFTCURLY */
{  yy_destructor(yypParser,31,&yymsp[0].minor);
{ wInterface->PushOp(tKind::LeftCurly); }
}
        break;
      case 73: /* openpipe ::= PIPE */
{  yy_destructor(yypParser,26,&yymsp[0].minor);
{ wInterface->PushOp(tKind::LeftCurly); }
}
        break;
      case 74: /* expr ::= openbrace listliteral RIGHTCURLY */
{ wInterface->PushOp(tKind::RightCurly); }
  yy_destructor(yypParser,32,&yymsp[0].minor);
        break;
      case 75: /* expr ::= openpipe listliteral PIPE */
{ wInterface->PushOp(tKind::RightCurly); }
  yy_destructor(yypParser,26,&yymsp[0].minor);
        break;
      case 76: /* exprList ::= expr */
{wInterface->IncArg(); }
        break;
      case 77: /* exprList ::= exprList argsep expr */
{ wInterface->IncArg(); }
        break;
      case 78: /* exprList ::= exprList argsep */
{ wInterface->PushEmptyFunctionArg(); wInterface->IncArg(); }
        break;
      case 79: /* funcBegin ::= ID LEFTPARENT */
{ wInterface->PushFunctionMethod(yymsp[-1].minor.yy0.m_Token->Lexeme(),false); }
  yy_destructor(yypParser,28,&yymsp[0].minor);
        break;
      case 80: /* funcEnd ::= exprList RIGHTPARENT */
{ 
  tLemonFunctionMethod wLemonFunctionMethod(wInterface->PopFunctionMethod());
  wInterface->PushFunctionMethod(&wLemonFunctionMethod); 
}
  yy_destructor(yypParser,30,&yymsp[0].minor);
        break;
      case 82: /* letBegin ::= LET LEFTPARENT */
{  yy_destructor(yypParser,39,&yymsp[-1].minor);
{ wInterface->LetBeginScope(); }
  yy_destructor(yypParser,28,&yymsp[0].minor);
}
        break;
      case 83: /* letBinding ::= ID argsep expr */
{ wInterface->LetBind(yymsp[-2].minor.yy0.m_Token->Lexeme()); }
        break;
      case 84: /* expr ::= letBegin letBindings argsep expr RIGHTPARENT */
{ wInterface->LetEndScope(); }
  yy_destructor(yypParser,30,&yymsp[0].minor);
        break;
      case 88: /* attribute ::= ATTRIBUTE */
{  yy_destructor(yypParser,6,&yymsp[0].minor);
{
}
}
        break;
      case 89: /* tableid ::= ID */
{  yy_destructor(yypParser,1,&yymsp[0].minor);
{
}
}
        break;
      case 90: /* tableid ::= LABELSQ */
{  yy_destructor(yypParser,3,&yymsp[0].minor);
{
}
}
        break;
      case 91: /* tableid ::= LABELDQ */
{  yy_destructor(yypParser,2,&yymsp[0].minor);
{
}
}
        break;
      case 98: /* argsep ::= COMMA */
{  yy_destructor(yypParser,24,&yymsp[0].minor);
{
}
}
        break;
      case 99: /* argsep ::= SEMICOLON */
{  yy_destructor(yypParser,25,&yymsp[0].minor);
{
}
}
        break;
      default:
      /* (85) main ::= in */ yytestcase(yyruleno==85);
      /* (86) in ::= */ yytestcase(yyruleno==86);
      /* (87) state ::= percent_prefix conditionalformat */ yytestcase(yyruleno==87);
      /* (92) expr ::= table */ yytestcase(yyruleno==92);
      /* (93) expr ::= thisrowcol (OPTIMIZED OUT) */ assert(yyruleno!=93);
      /* (94) listliteral ::= */ yytestcase(yyruleno==94);
      /* (95) listliteral ::= listcell (OPTIMIZED OUT) */ assert(yyruleno!=95);
      /* (96) listliteral ::= listcomma listcell */ yytestcase(yyruleno==96);
      /* (97) listliteral ::= listsemi listcell */ yytestcase(yyruleno==97);
      /* (100) exprList ::= */ yytestcase(yyruleno==100);
      /* (101) letBindings ::= letBinding (OPTIMIZED OUT) */ assert(yyruleno!=101);
      /* (102) letBindings ::= letBindings argsep letBinding */ yytestcase(yyruleno==102);
        break;
/********** End reduce actions ************************************************/
  };
  assert( yyruleno<sizeof(yyRuleInfoLhs)/sizeof(yyRuleInfoLhs[0]) );
  yygoto = yyRuleInfoLhs[yyruleno];
  yysize = yyRuleInfoNRhs[yyruleno];
  yyact = yy_find_reduce_action(yymsp[yysize].stateno,(YYCODETYPE)yygoto);

  /* There are no SHIFTREDUCE actions on nonterminals because the table
  ** generator has simplified them to pure REDUCE actions. */
  assert( !(yyact>YY_MAX_SHIFT && yyact<=YY_MAX_SHIFTREDUCE) );

  /* It is not possible for a REDUCE to be followed by an error */
  assert( yyact!=YY_ERROR_ACTION );

  yymsp += yysize+1;
  yypParser->yytos = yymsp;
  yymsp->stateno = (YYACTIONTYPE)yyact;
  yymsp->major = (YYCODETYPE)yygoto;
  yyTraceShift(yypParser, yyact, "... then shift");
  return yyact;
}

/*
** The following code executes when the parse fails
*/
#ifndef YYNOERRORRECOVERY
static void yy_parse_failed(
  yyParser *yypParser           /* The parser */
){
  ParseARG_FETCH
  ParseCTX_FETCH
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sFail!\n",yyTracePrompt);
  }
#endif
  while( yypParser->yytos>yypParser->yystack ) yy_pop_parser_stack(yypParser);
  /* Here code is inserted which will be executed whenever the
  ** parser fails */
/************ Begin %parse_failure code ***************************************/
/************ End %parse_failure code *****************************************/
  ParseARG_STORE /* Suppress warning about unused %extra_argument variable */
  ParseCTX_STORE
}
#endif /* YYNOERRORRECOVERY */

/*
** The following code executes when a syntax error first occurs.
*/
static void yy_syntax_error(
  yyParser *yypParser,           /* The parser */
  int yymajor,                   /* The major type of the error token */
  ParseTOKENTYPE yyminor         /* The minor type of the error token */
){
  ParseARG_FETCH
  ParseCTX_FETCH
#define TOKEN yyminor
/************ Begin %syntax_error code ****************************************/
  
  wInterface->CompilError(tErrorFormula::t_SyntaxError);
  wInterface->Error("Syntax error !",wLexLine,wLexColumn);
/************ End %syntax_error code ******************************************/
  ParseARG_STORE /* Suppress warning about unused %extra_argument variable */
  ParseCTX_STORE
}

/*
** The following is executed when the parser accepts
*/
static void yy_accept(
  yyParser *yypParser           /* The parser */
){
  ParseARG_FETCH
  ParseCTX_FETCH
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sAccept!\n",yyTracePrompt);
  }
#endif
#ifndef YYNOERRORRECOVERY
  yypParser->yyerrcnt = -1;
#endif
  assert( yypParser->yytos==yypParser->yystack );
  /* Here code is inserted which will be executed whenever the
  ** parser accepts */
/*********** Begin %parse_accept code *****************************************/

  // code for accept
/*********** End %parse_accept code *******************************************/
  ParseARG_STORE /* Suppress warning about unused %extra_argument variable */
  ParseCTX_STORE
}

/* The main parser program.
** The first argument is a pointer to a structure obtained from
** "ParseAlloc" which describes the current state of the parser.
** The second argument is the major token number.  The third is
** the minor token.  The fourth optional argument is whatever the
** user wants (and specified in the grammar) and is available for
** use by the action routines.
**
** Inputs:
** <ul>
** <li> A pointer to the parser (an opaque structure.)
** <li> The major token number.
** <li> The minor token number.
** <li> An option argument of a grammar-specified type.
** </ul>
**
** Outputs:
** None.
*/
void Parse(
  void *yyp,                   /* The parser */
  int yymajor,                 /* The major token code number */
  ParseTOKENTYPE yyminor       /* The value for the token */
  ParseARG_PDECL               /* Optional %extra_argument parameter */
){
  YYMINORTYPE yyminorunion;
  YYACTIONTYPE yyact;   /* The parser action. */
#if !defined(YYERRORSYMBOL) && !defined(YYNOERRORRECOVERY)
  int yyendofinput;     /* True if we are at the end of input */
#endif
#ifdef YYERRORSYMBOL
  int yyerrorhit = 0;   /* True if yymajor has invoked an error */
#endif
  yyParser *yypParser = (yyParser*)yyp;  /* The parser */
  ParseCTX_FETCH
  ParseARG_STORE

  assert( yypParser->yytos!=0 );
#if !defined(YYERRORSYMBOL) && !defined(YYNOERRORRECOVERY)
  yyendofinput = (yymajor==0);
#endif

  yyact = yypParser->yytos->stateno;
#ifndef NDEBUG
  if( yyTraceFILE ){
    if( yyact < YY_MIN_REDUCE ){
      fprintf(yyTraceFILE,"%sInput '%s' in state %d\n",
              yyTracePrompt,yyTokenName[yymajor],yyact);
    }else{
      fprintf(yyTraceFILE,"%sInput '%s' with pending reduce %d\n",
              yyTracePrompt,yyTokenName[yymajor],yyact-YY_MIN_REDUCE);
    }
  }
#endif

  do{
    assert( yyact==yypParser->yytos->stateno );
    yyact = yy_find_shift_action((YYCODETYPE)yymajor,yyact);
    if( yyact >= YY_MIN_REDUCE ){
      yyact = yy_reduce(yypParser,yyact-YY_MIN_REDUCE,yymajor,
                        yyminor ParseCTX_PARAM);
    }else if( yyact <= YY_MAX_SHIFTREDUCE ){
      yy_shift(yypParser,yyact,(YYCODETYPE)yymajor,yyminor);
#ifndef YYNOERRORRECOVERY
      yypParser->yyerrcnt--;
#endif
      break;
    }else if( yyact==YY_ACCEPT_ACTION ){
      yypParser->yytos--;
      yy_accept(yypParser);
      return;
    }else{
      assert( yyact == YY_ERROR_ACTION );
      yyminorunion.yy0 = yyminor;
#ifdef YYERRORSYMBOL
      int yymx;
#endif
#ifndef NDEBUG
      if( yyTraceFILE ){
        fprintf(yyTraceFILE,"%sSyntax Error!\n",yyTracePrompt);
      }
#endif
#ifdef YYERRORSYMBOL
      /* A syntax error has occurred.
      ** The response to an error depends upon whether or not the
      ** grammar defines an error token "ERROR".  
      **
      ** This is what we do if the grammar does define ERROR:
      **
      **  * Call the %syntax_error function.
      **
      **  * Begin popping the stack until we enter a state where
      **    it is legal to shift the error symbol, then shift
      **    the error symbol.
      **
      **  * Set the error count to three.
      **
      **  * Begin accepting and shifting new tokens.  No new error
      **    processing will occur until three tokens have been
      **    shifted successfully.
      **
      */
      if( yypParser->yyerrcnt<0 ){
        yy_syntax_error(yypParser,yymajor,yyminor);
      }
      yymx = yypParser->yytos->major;
      if( yymx==YYERRORSYMBOL || yyerrorhit ){
#ifndef NDEBUG
        if( yyTraceFILE ){
          fprintf(yyTraceFILE,"%sDiscard input token %s\n",
             yyTracePrompt,yyTokenName[yymajor]);
        }
#endif
        yy_destructor(yypParser, (YYCODETYPE)yymajor, &yyminorunion);
        yymajor = YYNOCODE;
      }else{
        while( yypParser->yytos >= yypParser->yystack
            && (yyact = yy_find_reduce_action(
                        yypParser->yytos->stateno,
                        YYERRORSYMBOL)) > YY_MAX_SHIFTREDUCE
        ){
          yy_pop_parser_stack(yypParser);
        }
        if( yypParser->yytos < yypParser->yystack || yymajor==0 ){
          yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
          yy_parse_failed(yypParser);
#ifndef YYNOERRORRECOVERY
          yypParser->yyerrcnt = -1;
#endif
          yymajor = YYNOCODE;
        }else if( yymx!=YYERRORSYMBOL ){
          yy_shift(yypParser,yyact,YYERRORSYMBOL,yyminor);
        }
      }
      yypParser->yyerrcnt = 3;
      yyerrorhit = 1;
      if( yymajor==YYNOCODE ) break;
      yyact = yypParser->yytos->stateno;
#elif defined(YYNOERRORRECOVERY)
      /* If the YYNOERRORRECOVERY macro is defined, then do not attempt to
      ** do any kind of error recovery.  Instead, simply invoke the syntax
      ** error routine and continue going as if nothing had happened.
      **
      ** Applications can set this macro (for example inside %include) if
      ** they intend to abandon the parse upon the first syntax error seen.
      */
      yy_syntax_error(yypParser,yymajor, yyminor);
      yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
      break;
#else  /* YYERRORSYMBOL is not defined */
      /* This is what we do if the grammar does not define ERROR:
      **
      **  * Report an error message, and throw away the input token.
      **
      **  * If the input token is $, then fail the parse.
      **
      ** As before, subsequent error messages are suppressed until
      ** three input tokens have been successfully shifted.
      */
      if( yypParser->yyerrcnt<=0 ){
        yy_syntax_error(yypParser,yymajor, yyminor);
      }
      yypParser->yyerrcnt = 3;
      yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
      if( yyendofinput ){
        yy_parse_failed(yypParser);
#ifndef YYNOERRORRECOVERY
        yypParser->yyerrcnt = -1;
#endif
      }
      break;
#endif
    }
  }while( yypParser->yytos>yypParser->yystack );
#ifndef NDEBUG
  if( yyTraceFILE ){
    yyStackEntry *i;
    char cDiv = '[';
    fprintf(yyTraceFILE,"%sReturn. Stack=",yyTracePrompt);
    for(i=&yypParser->yystack[1]; i<=yypParser->yytos; i++){
      fprintf(yyTraceFILE,"%c%s", cDiv, yyTokenName[i->major]);
      cDiv = ' ';
    }
    fprintf(yyTraceFILE,"]\n");
  }
#endif
  return;
}

/*
** Return the fallback token corresponding to canonical token iToken, or
** 0 if iToken has no fallback.
*/
int ParseFallback(int iToken){
#ifdef YYFALLBACK
  assert( iToken<(int)(sizeof(yyFallback)/sizeof(yyFallback[0])) );
  return yyFallback[iToken];
#else
  (void)iToken;
  return 0;
#endif
}
