#define ID                               1
#define LABELDQ                          2
#define LABELSQ                          3
#define LABELSQUARE                      4
#define CELL                             5
#define ATTRIBUTE                        6
#define ERRORREF                         7
#define ERRORNAME                        8
#define PERCENT                          9
#define AT                              10
#define HASH                            11
#define EQUAL                           12
#define NOTEQUAL                        13
#define GREATER                         14
#define GREATEREQUAL                    15
#define LESS                            16
#define LESSEQUAL                       17
#define AMPERSAND                       18
#define PLUS                            19
#define MINUS                           20
#define TIMES                           21
#define DIVIDE                          22
#define MOD                             23
#define COMMA                           24
#define SEMICOLON                       25
#define PIPE                            26
#define LEFTSQUARE                      27
#define LEFTPARENT                      28
#define RIGHTSQUARE                     29
#define RIGHTPARENT                     30
#define LEFTCURLY                       31
#define RIGHTCURLY                      32
#define END                             33
#define INTEGER                         34
#define FLOAT                           35
#define BOOL                            36
#define SHEET                           37
#define COLON                           38
#define LET                             39
