//==============================================================================
// TestSkCell
// le 31/10/2021 
//==============================================================================
#ifndef TestSkExcel_hpp
#define TestSkExcel_hpp

#include <cppunit/extensions/HelperMacros.h>

#include <SkApplication.hpp>
#include <SkApi.hpp>

using namespace SkRoot;
using namespace SkSpreadSheet;

class TestSkExcel : public CPPUNIT_NS::TestFixture {
	// Sequence of tests
	CPPUNIT_TEST_SUITE(TestSkExcel);
	//CPPUNIT_TEST(TestFormula);
    //CPPUNIT_TEST(TestFunction);
//#ifndef __EMSCRIPTEN__
    //CPPUNIT_TEST(LoadPret);
    //CPPUNIT_TEST(LoadAmort);
    //CPPUNIT_TEST(LoadBudgetNamedFormulas);
    CPPUNIT_TEST(LoadBudget);
    CPPUNIT_TEST(LoadBudgetInterfaceWeb);
    CPPUNIT_TEST(LoadBudgetDeleteRowUndo);
    CPPUNIT_TEST(LoadBudgetDeleteRowUndo16_19);
    CPPUNIT_TEST(LoadBudgetDeleteRowUndoGetMessage);
    CPPUNIT_TEST(LoadBudgetDeleteRowByRectUndoGetMessage);
    CPPUNIT_TEST(LoadBudgetDeleteRowByRectD16UndoGetMessage);
    CPPUNIT_TEST(LoadBudgetDeleteRowByRectMergeD16);
    CPPUNIT_TEST(LoadBudgetDeleteRow7_10);
    CPPUNIT_TEST(LoadBudgetDeleteColF);
    CPPUNIT_TEST(LoadBudgetDeleteColHToL);
    CPPUNIT_TEST(LoadBudgetDeleteColJToM);
#ifdef TestMultiUser
    CPPUNIT_TEST(LoadBudgetInterfaceWebMultiUser);
#endif
    //CPPUNIT_TEST(PDFMetrics);
    //CPPUNIT_TEST(LoadConditionalHighlightCells); // Needs libSkFormat (not linked here); see body.
    //CPPUNIT_TEST(LoadJsonResult);
//#endif
	CPPUNIT_TEST_SUITE_END();
private:
	tApplication* m_Application; // Pointer of static application
	tApi* m_Api;
	tFormatApi* m_FormatApi;
        
public:
	TestSkExcel();
private:
    void DebugCell(tString sRef);
    /// Git-style unified line diff (LCS); falls back to first byte mismatch with context for huge or single-line JSON.
    void DumpStringDiffGitHubStyle(const tString& sLabelLeft, const tString& sLeft,
                                   const tString& sLabelRight, const tString& sRight) const;
    
	void DrawCell(tString sTitle,tInt sRowBegin, tInt sColBegin, tInt sRowEnd, tInt sColEnd);
	void UndoOperation();

	void TestFormula();
    void TestFunction();
#ifndef __EMSCRIPTEN__
    void LoadPret();
    void LoadJsonResult();
#endif
    void LoadAmort();
    
    void LoadBudget();
    /// Same scenario as LoadBudget but Undo goes through tInterfaceWeb (Client + Rebase), like the browser WASM path.
    void LoadBudgetInterfaceWeb();
    /// Delete rows 16–22 on Rapport financier then undo; checks restore (not empty) and no duplicate labels.
    void LoadBudgetDeleteRowUndo();
    /// Delete rows 16–19 (4 rows) on Rapport financier — user/server regression scenario.
    void LoadBudgetDeleteRowUndo16_19();
    /// Server/collaborative path: undo delete row via GetMessage(JSON) without local Undo() first.
    void LoadBudgetDeleteRowUndoGetMessage();
    /// Server path: undo delete row D15:F17 by rect via GetMessage(JSON).
    void LoadBudgetDeleteRowByRectUndoGetMessage();
    /// Server path: undo delete row D16 only by rect via GetMessage(JSON).
    void LoadBudgetDeleteRowByRectD16UndoGetMessage();
    /// Delete D16 shift-up then undo: merge I16:L16 (sparklines) must survive outside the deleted column band.
    void LoadBudgetDeleteRowByRectMergeD16();
    /// Delete rows 7–10 on Rapport financier (merges J7:L10 + CF row 9 icons); symmetric stress to delete col H:L.
    void LoadBudgetDeleteRow7_10();
    /// Delete column F on Rapport financier (CF ranges in deleted column); regression for checksp F9:F9.
    void LoadBudgetDeleteColF();
    void LoadBudgetDeleteColHToL();
    void LoadBudgetDeleteColJToM();
#ifdef TestMultiUser
    /// Multi-user WASM path: Undo paste/move via PopUndoToRedoWithoutExecute + GetMessage (not local Undo()).
    void LoadBudgetInterfaceWebMultiUser();
#endif
    /// Diagnostic: load /Projects/Excel/Budget.sker (auto-generated by SkExcel from Budget.xlsx) and verify
    /// that named-formula-driven cells (Calculs!D3, D4, C6:G6 use MATCH(...,lstAnnées,0)+1) evaluate
    /// without #ARG / #REF / #VALEUR errors. Skipped silently when the Budget.sker payload is absent.
    void LoadBudgetNamedFormulas();
    /// Regression for Conditional.sker (Apr 2026): after the named-formula spill work, the WASM
    /// build stopped painting HighlightCellsRules in the browser ("il marchait hier"). The native
    /// TestHighlightCellsRulesJsonViewRendering test only goes through UndoConditionalFormat — it
    /// never exercises the .sker JSON load path. This test loads Conditional.sker directly and
    /// asserts that C2/D2 still receive the f_bc / f_c attributes from the rule's true branch.
    void LoadConditionalHighlightCells();
   
    void PDFMetrics();
//#endif
public:
	void setUp();
	void tearDown();
};


#endif    /* TestSkCell */
