#define F_ID                             1
#define F_LABELDQ                        2
#define F_LABELSQ                        3
#define F_DOT                            4
#define F_COMMA                          5
#define F_COLON                          6
#define F_EXCLAMATION                    7
#define F_NEWLINE                        8
#define F_COMMENT                        9
#define F_WIDTH                         10
#define F_HEIGHT                        11
#define F_BACKGROUNDCOLOR               12
#define F_COLOR                         13
#define F_OPACITY                       14
#define F_COLORSTR                      15
#define F_COLORHASH                     16
#define F_RGB                           17
#define F_RGBA                          18
#define F_TEXT_ALIGN                    19
#define F_LEFT                          20
#define F_RIGHT                         21
#define F_CENTER                        22
#define F_JUSTIFY                       23
#define F_VERTICAL_ALIGN                24
#define F_BASELINE                      25
#define F_SUB                           26
#define F_SUPER                         27
#define F_TEXT_TOP                      28
#define F_TEXT_BOTTOM                   29
#define F_TOP                           30
#define F_BOTTOM                        31
#define F_MIDDLE                        32
#define F_DECORATION_LINE               33
#define F_UNDERLINE                     34
#define F_OVERLINE                      35
#define F_LINE_THROUGH                  36
#define F_TEXT_WRAP                     37
#define F_WRAP                          38
#define F_NO_WRAP                       39
#define F_TEXT_ROTATE                   40
#define F_FONT                          41
#define F_FONT_NAME                     42
#define F_FONT_FAMILY                   43
#define F_SERIF                         44
#define F_SANS_SERIF                    45
#define F_MONOSPACE                     46
#define F_CURSIVE                       47
#define F_FANTASY                       48
#define F_SYSTEM_UI                     49
#define F_EMOJI                         50
#define F_MATH                          51
#define F_FANGSONG                      52
#define F_FONT_SIZE                     53
#define F_FONT_STYLE                    54
#define F_NORMAL                        55
#define F_ITALIC                        56
#define F_OBLIQUE                       57
#define F_PERCENT                       58
#define F_FONT_VARIANT                  59
#define F_SMALL_CAPS                    60
#define F_FONT_STRETCH                  61
#define F_ULTRA_CONDENSED               62
#define F_CONDENSED                     63
#define F_SEMI_CONDENSED                64
#define F_SEMI_EXPANDED                 65
#define F_EXPANDED                      66
#define F_EXTRA_EXPANDED                67
#define F_ULTRA_EXPANDED                68
#define F_LINE_HEIGHT                   69
#define F_WEIGHT                        70
#define F_BOLD                          71
#define F_LIGHTER                       72
#define F_BOLDER                        73
#define F_BORDER                        74
#define F_BORDER_LEFT                   75
#define F_BORDER_TOP                    76
#define F_BORDER_RIGHT                  77
#define F_BORDER_BOTTOM                 78
#define F_BORDER_RADIUS                 79
#define F_BORDER_TOP_LEFT_RADIUS        80
#define F_BORDER_TOP_RIGHT_RADIUS       81
#define F_BORDER_BOTTOM_LEFT_RADIUS     82
#define F_BORDER_BOTTOM_RIGHT_RADIUS    83
#define F_NONE                          84
#define F_HIDDEN                        85
#define F_DOTTED                        86
#define F_DASHED                        87
#define F_SOLID                         88
#define F_DOUBLE                        89
#define F_GROOVE                        90
#define F_RIDGE                         91
#define F_INSET                         92
#define F_OUTSET                        93
#define F_FORMATSTRING                  94
#define F_MARGIN                        95
#define F_MARGIN_LEFT                   96
#define F_MARGIN_TOP                    97
#define F_MARGIN_RIGHT                  98
#define F_MARGIN_BOTTOM                 99
#define F_PADDING                      100
#define F_PADDING_LEFT                 101
#define F_PADDING_TOP                  102
#define F_PADDING_RIGHT                103
#define F_PADDING_BOTTOM               104
#define F_PX                           105
#define F_IN                           106
#define F_PT                           107
#define F_PC                           108
#define F_CM                           109
#define F_MM                           110
#define F_EM                           111
#define F_DEG                          112
#define F_HOVER                        113
#define F_FOCUS                        114
#define F_SEMICOLON                    115
#define F_RIGHTCURLY                   116
#define F_LEFTCURLY                    117
#define F_RIGHTPARENT                  118
#define F_RIGHTSQUARE                  119
#define F_AMPERSAND                    120
#define F_LEFTPARENT                   121
#define F_LEFTSQUARE                   122
#define F_EXP                          123
#define F_NOT                          124
#define F_END                          125
#define F_HASH                         126
#define F_INTEGER                      127
#define F_FLOAT                        128
